namespace DO_AN_CUA_HAN.View
{
    partial class FormRoleDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormRoleDetail));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.listBoxSystemFunctionID = new System.Windows.Forms.ListBox();
            this.listBoxCurrentFunctionID = new System.Windows.Forms.ListBox();
            this.listBoxSystemFunction = new System.Windows.Forms.ListBox();
            this.listBoxCurrentFunction = new System.Windows.Forms.ListBox();
            this.buttonInsertFunction = new Bunifu.UI.WinForms.BunifuImageButton();
            this.buttonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonOk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.labelRoleName = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxRoleName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBoxRoleID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelRoleID = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.buttonRemoveFunction = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 50;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(157)))), ((int)(((byte)(191)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(109)))), ((int)(((byte)(160)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(677, 741);
            this.bunifuGradientPanel1.TabIndex = 1;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel1.BorderRadius = 20;
            this.bunifuShadowPanel1.BorderThickness = 2;
            this.bunifuShadowPanel1.Controls.Add(this.listBoxSystemFunctionID);
            this.bunifuShadowPanel1.Controls.Add(this.listBoxCurrentFunctionID);
            this.bunifuShadowPanel1.Controls.Add(this.listBoxSystemFunction);
            this.bunifuShadowPanel1.Controls.Add(this.listBoxCurrentFunction);
            this.bunifuShadowPanel1.Controls.Add(this.buttonInsertFunction);
            this.bunifuShadowPanel1.Controls.Add(this.buttonClose);
            this.bunifuShadowPanel1.Controls.Add(this.buttonOk);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel7);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuShadowPanel1.Controls.Add(this.labelRoleName);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxRoleName);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxRoleID);
            this.bunifuShadowPanel1.Controls.Add(this.labelRoleID);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.buttonRemoveFunction);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(36, 42);
            this.bunifuShadowPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(592, 653);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuShadowPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuShadowPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuShadowPanel1, "");
            // 
            // listBoxSystemFunctionID
            // 
            this.listBoxSystemFunctionID.FormattingEnabled = true;
            this.listBoxSystemFunctionID.Location = new System.Drawing.Point(104, 569);
            this.listBoxSystemFunctionID.Name = "listBoxSystemFunctionID";
            this.listBoxSystemFunctionID.Size = new System.Drawing.Size(44, 43);
            this.listBoxSystemFunctionID.TabIndex = 67;
            this.bunifuToolTip1.SetToolTip(this.listBoxSystemFunctionID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.listBoxSystemFunctionID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.listBoxSystemFunctionID, "");
            // 
            // listBoxCurrentFunctionID
            // 
            this.listBoxCurrentFunctionID.FormattingEnabled = true;
            this.listBoxCurrentFunctionID.Location = new System.Drawing.Point(39, 569);
            this.listBoxCurrentFunctionID.Name = "listBoxCurrentFunctionID";
            this.listBoxCurrentFunctionID.Size = new System.Drawing.Size(44, 43);
            this.listBoxCurrentFunctionID.TabIndex = 66;
            this.bunifuToolTip1.SetToolTip(this.listBoxCurrentFunctionID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.listBoxCurrentFunctionID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.listBoxCurrentFunctionID, "");
            // 
            // listBoxSystemFunction
            // 
            this.listBoxSystemFunction.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(231)))), ((int)(((byte)(219)))));
            this.listBoxSystemFunction.ForeColor = System.Drawing.Color.Black;
            this.listBoxSystemFunction.FormattingEnabled = true;
            this.listBoxSystemFunction.Location = new System.Drawing.Point(351, 289);
            this.listBoxSystemFunction.Margin = new System.Windows.Forms.Padding(2);
            this.listBoxSystemFunction.Name = "listBoxSystemFunction";
            this.listBoxSystemFunction.Size = new System.Drawing.Size(204, 251);
            this.listBoxSystemFunction.TabIndex = 65;
            this.bunifuToolTip1.SetToolTip(this.listBoxSystemFunction, "");
            this.bunifuToolTip1.SetToolTipIcon(this.listBoxSystemFunction, null);
            this.bunifuToolTip1.SetToolTipTitle(this.listBoxSystemFunction, "");
            // 
            // listBoxCurrentFunction
            // 
            this.listBoxCurrentFunction.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(231)))), ((int)(((byte)(219)))));
            this.listBoxCurrentFunction.ForeColor = System.Drawing.Color.Black;
            this.listBoxCurrentFunction.FormattingEnabled = true;
            this.listBoxCurrentFunction.Location = new System.Drawing.Point(39, 289);
            this.listBoxCurrentFunction.Margin = new System.Windows.Forms.Padding(2);
            this.listBoxCurrentFunction.Name = "listBoxCurrentFunction";
            this.listBoxCurrentFunction.Size = new System.Drawing.Size(204, 251);
            this.listBoxCurrentFunction.TabIndex = 64;
            this.bunifuToolTip1.SetToolTip(this.listBoxCurrentFunction, "");
            this.bunifuToolTip1.SetToolTipIcon(this.listBoxCurrentFunction, null);
            this.bunifuToolTip1.SetToolTipTitle(this.listBoxCurrentFunction, "");
            // 
            // buttonInsertFunction
            // 
            this.buttonInsertFunction.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonInsertFunction.ActiveImage = null;
            this.buttonInsertFunction.AllowAnimations = true;
            this.buttonInsertFunction.AllowBuffering = false;
            this.buttonInsertFunction.AllowToggling = false;
            this.buttonInsertFunction.AllowZooming = false;
            this.buttonInsertFunction.AllowZoomingOnFocus = false;
            this.buttonInsertFunction.BackColor = System.Drawing.Color.Transparent;
            this.buttonInsertFunction.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.buttonInsertFunction.Cursor = System.Windows.Forms.Cursors.Hand;
            this.buttonInsertFunction.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonInsertFunction.ErrorImage = ((System.Drawing.Image)(resources.GetObject("buttonInsertFunction.ErrorImage")));
            this.buttonInsertFunction.FadeWhenInactive = true;
            this.buttonInsertFunction.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.buttonInsertFunction.Image = global::DO_AN_CUA_HAN.Properties.Resources._81328514_removebg_preview;
            this.buttonInsertFunction.ActiveImage = null;
            this.buttonInsertFunction.ImageLocation = null;
            this.buttonInsertFunction.ImageMargin = 40;
            this.buttonInsertFunction.ImageSize = new System.Drawing.Size(74, 63);
            this.buttonInsertFunction.ImageZoomSize = new System.Drawing.Size(114, 103);
            this.buttonInsertFunction.InitialImage = ((System.Drawing.Image)(resources.GetObject("buttonInsertFunction.InitialImage")));
            this.buttonInsertFunction.Location = new System.Drawing.Point(238, 291);
            this.buttonInsertFunction.Margin = new System.Windows.Forms.Padding(2);
            this.buttonInsertFunction.Name = "buttonInsertFunction";
            this.buttonInsertFunction.Rotation = 0;
            this.buttonInsertFunction.ShowActiveImage = true;
            this.buttonInsertFunction.ShowCursorChanges = false;
            this.buttonInsertFunction.ShowImageBorders = false;
            this.buttonInsertFunction.ShowSizeMarkers = false;
            this.buttonInsertFunction.Size = new System.Drawing.Size(114, 103);
            this.buttonInsertFunction.TabIndex = 61;
            this.bunifuToolTip1.SetToolTip(this.buttonInsertFunction, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonInsertFunction, null);
            this.buttonInsertFunction.ToolTipText = "";
            this.bunifuToolTip1.SetToolTipTitle(this.buttonInsertFunction, "");
            this.buttonInsertFunction.WaitOnLoad = false;
            this.buttonInsertFunction.ImageMargin = 40;
            this.buttonInsertFunction.ZoomSpeed = 10;
            this.buttonInsertFunction.Click += new System.EventHandler(this.buttonInsertFunction_Click);
            // 
            // buttonClose
            // 
            this.buttonClose.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonClose.AllowAnimations = true;
            this.buttonClose.AllowMouseEffects = true;
            this.buttonClose.AllowToggling = false;
            this.buttonClose.AnimationSpeed = 200;
            this.buttonClose.AutoGenerateColors = false;
            this.buttonClose.AutoRoundBorders = false;
            this.buttonClose.AutoSizeLeftIcon = true;
            this.buttonClose.AutoSizeRightIcon = true;
            this.buttonClose.BackColor = System.Drawing.Color.Transparent;
            this.buttonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonClose.BackgroundImage")));
            this.buttonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.ButtonText = "Thoát";
            this.buttonClose.ButtonTextMarginLeft = 0;
            this.buttonClose.ColorContrastOnClick = 45;
            this.buttonClose.ColorContrastOnHover = 45;
            this.buttonClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonClose.CustomizableEdges = borderEdges1;
            this.buttonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonClose.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonClose.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonClose.IconMarginLeft = 11;
            this.buttonClose.IconPadding = 10;
            this.buttonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonClose.IconSize = 25;
            this.buttonClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleBorderRadius = 15;
            this.buttonClose.IdleBorderThickness = 1;
            this.buttonClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleIconLeftImage = null;
            this.buttonClose.IdleIconRightImage = null;
            this.buttonClose.IndicateFocus = false;
            this.buttonClose.Location = new System.Drawing.Point(492, 575);
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.OnDisabledState.BorderRadius = 15;
            this.buttonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnDisabledState.BorderThickness = 1;
            this.buttonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.OnDisabledState.IconLeftImage = null;
            this.buttonClose.OnDisabledState.IconRightImage = null;
            this.buttonClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonClose.onHoverState.BorderRadius = 15;
            this.buttonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.onHoverState.BorderThickness = 1;
            this.buttonClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonClose.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonClose.onHoverState.IconLeftImage = null;
            this.buttonClose.onHoverState.IconRightImage = null;
            this.buttonClose.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.BorderRadius = 15;
            this.buttonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnIdleState.BorderThickness = 1;
            this.buttonClose.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonClose.OnIdleState.IconLeftImage = null;
            this.buttonClose.OnIdleState.IconRightImage = null;
            this.buttonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.BorderRadius = 15;
            this.buttonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnPressedState.BorderThickness = 1;
            this.buttonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonClose.OnPressedState.IconLeftImage = null;
            this.buttonClose.OnPressedState.IconRightImage = null;
            this.buttonClose.Size = new System.Drawing.Size(63, 37);
            this.buttonClose.TabIndex = 58;
            this.buttonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonClose.TextMarginLeft = 0;
            this.buttonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.buttonClose, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonClose, null);
            this.bunifuToolTip1.SetToolTipTitle(this.buttonClose, "");
            this.buttonClose.UseDefaultRadiusAndThickness = true;
            this.buttonClose.Click += new System.EventHandler(this.buttonClose_Click);
            // 
            // buttonOk
            // 
            this.buttonOk.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonOk.AllowAnimations = true;
            this.buttonOk.AllowMouseEffects = true;
            this.buttonOk.AllowToggling = false;
            this.buttonOk.AnimationSpeed = 200;
            this.buttonOk.AutoGenerateColors = false;
            this.buttonOk.AutoRoundBorders = false;
            this.buttonOk.AutoSizeLeftIcon = true;
            this.buttonOk.AutoSizeRightIcon = true;
            this.buttonOk.BackColor = System.Drawing.Color.Transparent;
            this.buttonOk.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonOk.BackgroundImage")));
            this.buttonOk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.ButtonText = "Đồng ý";
            this.buttonOk.ButtonTextMarginLeft = 0;
            this.buttonOk.ColorContrastOnClick = 45;
            this.buttonOk.ColorContrastOnHover = 45;
            this.buttonOk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonOk.CustomizableEdges = borderEdges2;
            this.buttonOk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonOk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonOk.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonOk.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonOk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonOk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonOk.IconMarginLeft = 11;
            this.buttonOk.IconPadding = 10;
            this.buttonOk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonOk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonOk.IconSize = 25;
            this.buttonOk.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleBorderRadius = 15;
            this.buttonOk.IdleBorderThickness = 1;
            this.buttonOk.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleIconLeftImage = null;
            this.buttonOk.IdleIconRightImage = null;
            this.buttonOk.IndicateFocus = false;
            this.buttonOk.Location = new System.Drawing.Point(394, 575);
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.OnDisabledState.BorderRadius = 15;
            this.buttonOk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnDisabledState.BorderThickness = 1;
            this.buttonOk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.OnDisabledState.IconLeftImage = null;
            this.buttonOk.OnDisabledState.IconRightImage = null;
            this.buttonOk.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonOk.onHoverState.BorderRadius = 15;
            this.buttonOk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.onHoverState.BorderThickness = 1;
            this.buttonOk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonOk.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonOk.onHoverState.IconLeftImage = null;
            this.buttonOk.onHoverState.IconRightImage = null;
            this.buttonOk.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.BorderRadius = 15;
            this.buttonOk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnIdleState.BorderThickness = 1;
            this.buttonOk.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonOk.OnIdleState.IconLeftImage = null;
            this.buttonOk.OnIdleState.IconRightImage = null;
            this.buttonOk.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.BorderRadius = 15;
            this.buttonOk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnPressedState.BorderThickness = 1;
            this.buttonOk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonOk.OnPressedState.IconLeftImage = null;
            this.buttonOk.OnPressedState.IconRightImage = null;
            this.buttonOk.Size = new System.Drawing.Size(63, 37);
            this.buttonOk.TabIndex = 57;
            this.buttonOk.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonOk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonOk.TextMarginLeft = 0;
            this.buttonOk.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.buttonOk, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonOk, null);
            this.bunifuToolTip1.SetToolTipTitle(this.buttonOk, "");
            this.buttonOk.UseDefaultRadiusAndThickness = true;
            this.buttonOk.Click += new System.EventHandler(this.buttonOk_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Thoát";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges3;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.IdleBorderRadius = 15;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(596, 766);
            this.bunifuButton2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 15;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 15;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 15;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 15;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(63, 37);
            this.bunifuButton2.TabIndex = 23;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton2, "");
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Đồng ý";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges4;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.IdleBorderRadius = 15;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(472, 767);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 15;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 15;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 15;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 15;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(63, 37);
            this.bunifuButton1.TabIndex = 22;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton1, "");
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel7.Location = new System.Drawing.Point(371, 257);
            this.bunifuLabel7.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(171, 17);
            this.bunifuLabel7.TabIndex = 20;
            this.bunifuLabel7.Text = "Các chức năng của hệ thống";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel7, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel7, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel7, "");
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel6.Location = new System.Drawing.Point(73, 257);
            this.bunifuLabel6.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(137, 17);
            this.bunifuLabel6.TabIndex = 19;
            this.bunifuLabel6.Text = "Các chức năng hiện có";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel6, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel6, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel6, "");
            // 
            // labelRoleName
            // 
            this.labelRoleName.AllowParentOverrides = false;
            this.labelRoleName.AutoEllipsis = false;
            this.labelRoleName.CursorType = null;
            this.labelRoleName.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelRoleName.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelRoleName.Location = new System.Drawing.Point(68, 198);
            this.labelRoleName.Name = "labelRoleName";
            this.labelRoleName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelRoleName.Size = new System.Drawing.Size(100, 17);
            this.labelRoleName.TabIndex = 16;
            this.labelRoleName.Text = "Tên phân quyền";
            this.labelRoleName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelRoleName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelRoleName, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelRoleName, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelRoleName, "");
            // 
            // textBoxRoleName
            // 
            this.textBoxRoleName.AcceptsReturn = false;
            this.textBoxRoleName.AcceptsTab = false;
            this.textBoxRoleName.AnimationSpeed = 200;
            this.textBoxRoleName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxRoleName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxRoleName.BackColor = System.Drawing.Color.White;
            this.textBoxRoleName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxRoleName.BackgroundImage")));
            this.textBoxRoleName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxRoleName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxRoleName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxRoleName.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxRoleName.BorderRadius = 10;
            this.textBoxRoleName.BorderThickness = 1;
            this.textBoxRoleName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxRoleName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxRoleName.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxRoleName.DefaultText = "";
            this.textBoxRoleName.FillColor = System.Drawing.Color.White;
            this.textBoxRoleName.ForeColor = System.Drawing.Color.Black;
            this.textBoxRoleName.HideSelection = true;
            this.textBoxRoleName.IconLeft = null;
            this.textBoxRoleName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxRoleName.IconPadding = 10;
            this.textBoxRoleName.IconRight = null;
            this.textBoxRoleName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxRoleName.Lines = new string[0];
            this.textBoxRoleName.Location = new System.Drawing.Point(195, 191);
            this.textBoxRoleName.MaxLength = 32767;
            this.textBoxRoleName.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxRoleName.Modified = false;
            this.textBoxRoleName.Multiline = false;
            this.textBoxRoleName.Name = "textBoxRoleName";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxRoleName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxRoleName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxRoleName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxRoleName.OnIdleState = stateProperties4;
            this.textBoxRoleName.Padding = new System.Windows.Forms.Padding(4);
            this.textBoxRoleName.PasswordChar = '\0';
            this.textBoxRoleName.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxRoleName.PlaceholderText = "Nhập tên phân quyền";
            this.textBoxRoleName.ReadOnly = false;
            this.textBoxRoleName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxRoleName.SelectedText = "";
            this.textBoxRoleName.SelectionLength = 0;
            this.textBoxRoleName.SelectionStart = 0;
            this.textBoxRoleName.ShortcutsEnabled = true;
            this.textBoxRoleName.Size = new System.Drawing.Size(310, 34);
            this.textBoxRoleName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxRoleName.TabIndex = 13;
            this.textBoxRoleName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxRoleName.TextMarginBottom = 0;
            this.textBoxRoleName.TextMarginLeft = 3;
            this.textBoxRoleName.TextMarginTop = 0;
            this.textBoxRoleName.TextPlaceholder = "Nhập tên phân quyền";
            this.bunifuToolTip1.SetToolTip(this.textBoxRoleName, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxRoleName, global::DO_AN_CUA_HAN.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxRoleName, "Warning");
            this.textBoxRoleName.UseSystemPasswordChar = false;
            this.textBoxRoleName.WordWrap = true;
            this.textBoxRoleName.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.textBoxRoleName_KeyPress);
            // 
            // textBoxRoleID
            // 
            this.textBoxRoleID.AcceptsReturn = false;
            this.textBoxRoleID.AcceptsTab = false;
            this.textBoxRoleID.AnimationSpeed = 200;
            this.textBoxRoleID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxRoleID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxRoleID.BackColor = System.Drawing.Color.White;
            this.textBoxRoleID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxRoleID.BackgroundImage")));
            this.textBoxRoleID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxRoleID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxRoleID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxRoleID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxRoleID.BorderRadius = 20;
            this.textBoxRoleID.BorderThickness = 1;
            this.textBoxRoleID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxRoleID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxRoleID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxRoleID.DefaultText = "";
            this.textBoxRoleID.FillColor = System.Drawing.Color.White;
            this.textBoxRoleID.ForeColor = System.Drawing.Color.Black;
            this.textBoxRoleID.HideSelection = true;
            this.textBoxRoleID.IconLeft = null;
            this.textBoxRoleID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxRoleID.IconPadding = 10;
            this.textBoxRoleID.IconRight = null;
            this.textBoxRoleID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxRoleID.Lines = new string[0];
            this.textBoxRoleID.Location = new System.Drawing.Point(195, 136);
            this.textBoxRoleID.MaxLength = 32767;
            this.textBoxRoleID.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxRoleID.Modified = false;
            this.textBoxRoleID.Multiline = false;
            this.textBoxRoleID.Name = "textBoxRoleID";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxRoleID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxRoleID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxRoleID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxRoleID.OnIdleState = stateProperties8;
            this.textBoxRoleID.Padding = new System.Windows.Forms.Padding(4);
            this.textBoxRoleID.PasswordChar = '\0';
            this.textBoxRoleID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxRoleID.PlaceholderText = "Nhập mã phân quyền";
            this.textBoxRoleID.ReadOnly = true;
            this.textBoxRoleID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxRoleID.SelectedText = "";
            this.textBoxRoleID.SelectionLength = 0;
            this.textBoxRoleID.SelectionStart = 0;
            this.textBoxRoleID.ShortcutsEnabled = true;
            this.textBoxRoleID.Size = new System.Drawing.Size(310, 34);
            this.textBoxRoleID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxRoleID.TabIndex = 12;
            this.textBoxRoleID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxRoleID.TextMarginBottom = 0;
            this.textBoxRoleID.TextMarginLeft = 3;
            this.textBoxRoleID.TextMarginTop = 0;
            this.textBoxRoleID.TextPlaceholder = "Nhập mã phân quyền";
            this.bunifuToolTip1.SetToolTip(this.textBoxRoleID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxRoleID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxRoleID, "");
            this.textBoxRoleID.UseSystemPasswordChar = false;
            this.textBoxRoleID.WordWrap = true;
            // 
            // labelRoleID
            // 
            this.labelRoleID.AllowParentOverrides = false;
            this.labelRoleID.AutoEllipsis = false;
            this.labelRoleID.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelRoleID.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelRoleID.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelRoleID.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelRoleID.Location = new System.Drawing.Point(73, 147);
            this.labelRoleID.Name = "labelRoleID";
            this.labelRoleID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelRoleID.Size = new System.Drawing.Size(95, 17);
            this.labelRoleID.TabIndex = 2;
            this.labelRoleID.Text = "Mã phân quyền";
            this.labelRoleID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelRoleID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelRoleID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelRoleID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelRoleID, "");
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cambria", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(270, 60);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(147, 28);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "PHÂN QUYỀN";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuPictureBox1.BorderRadius = 72;
            this.bunifuPictureBox1.Image = global::DO_AN_CUA_HAN.Properties.Resources._145411_OTQZ7A_227_removebg_preview;
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(131, -4);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(144, 144);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 56;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // buttonRemoveFunction
            // 
            this.buttonRemoveFunction.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonRemoveFunction.ActiveImage = null;
            this.buttonRemoveFunction.AllowAnimations = true;
            this.buttonRemoveFunction.AllowBuffering = false;
            this.buttonRemoveFunction.AllowToggling = false;
            this.buttonRemoveFunction.AllowZooming = false;
            this.buttonRemoveFunction.AllowZoomingOnFocus = false;
            this.buttonRemoveFunction.BackColor = System.Drawing.Color.Transparent;
            this.buttonRemoveFunction.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.buttonRemoveFunction.Cursor = System.Windows.Forms.Cursors.Hand;
            this.buttonRemoveFunction.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonRemoveFunction.ErrorImage = ((System.Drawing.Image)(resources.GetObject("buttonRemoveFunction.ErrorImage")));
            this.buttonRemoveFunction.FadeWhenInactive = true;
            this.buttonRemoveFunction.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.buttonRemoveFunction.Image = global::DO_AN_CUA_HAN.Properties.Resources._81328524_removebg_preview;
            this.buttonRemoveFunction.ActiveImage = null;
            this.buttonRemoveFunction.ImageLocation = null;
            this.buttonRemoveFunction.ImageMargin = 40;
            this.buttonRemoveFunction.ImageSize = new System.Drawing.Size(74, 63);
            this.buttonRemoveFunction.ImageZoomSize = new System.Drawing.Size(114, 103);
            this.buttonRemoveFunction.InitialImage = ((System.Drawing.Image)(resources.GetObject("buttonRemoveFunction.InitialImage")));
            this.buttonRemoveFunction.Location = new System.Drawing.Point(238, 439);
            this.buttonRemoveFunction.Margin = new System.Windows.Forms.Padding(2);
            this.buttonRemoveFunction.Name = "buttonRemoveFunction";
            this.buttonRemoveFunction.Rotation = 0;
            this.buttonRemoveFunction.ShowActiveImage = true;
            this.buttonRemoveFunction.ShowCursorChanges = false;
            this.buttonRemoveFunction.ShowImageBorders = false;
            this.buttonRemoveFunction.ShowSizeMarkers = false;
            this.buttonRemoveFunction.Size = new System.Drawing.Size(114, 103);
            this.buttonRemoveFunction.TabIndex = 60;
            this.bunifuToolTip1.SetToolTip(this.buttonRemoveFunction, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonRemoveFunction, null);
            this.buttonRemoveFunction.ToolTipText = "";
            this.bunifuToolTip1.SetToolTipTitle(this.buttonRemoveFunction, "");
            this.buttonRemoveFunction.WaitOnLoad = false;
            this.buttonRemoveFunction.ImageMargin = 40;
            this.buttonRemoveFunction.ZoomSpeed = 10;
            this.buttonRemoveFunction.Click += new System.EventHandler(this.buttonRemoveFunction_Click);
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(221)))), ((int)(((byte)(85)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.DimGray;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // FormRoleDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(677, 741);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormRoleDetail";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormRoleDetail";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel labelRoleName;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxRoleName;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxRoleID;
        private Bunifu.UI.WinForms.BunifuLabel labelRoleID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonOk;
        private Bunifu.UI.WinForms.BunifuImageButton buttonInsertFunction;
        private Bunifu.UI.WinForms.BunifuImageButton buttonRemoveFunction;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private System.Windows.Forms.ListBox listBoxCurrentFunction;
        private System.Windows.Forms.ListBox listBoxSystemFunction;
        private System.Windows.Forms.ListBox listBoxSystemFunctionID;
        private System.Windows.Forms.ListBox listBoxCurrentFunctionID;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
    }
}