namespace DO_AN_CUA_HAN.View
{
    partial class FormMedicineDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMedicineDetail));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBoxQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButtonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonOK = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel18 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBoxPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel22 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBoxMedicineName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxMedicineID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel23 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel24 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 50;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(157)))), ((int)(((byte)(191)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(109)))), ((int)(((byte)(160)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(616, 491);
            this.bunifuGradientPanel1.TabIndex = 2;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel2.BorderRadius = 20;
            this.bunifuShadowPanel2.BorderThickness = 2;
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuTextBoxQuantity);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuButtonClose);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuButtonOK);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel18);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuTextBoxPrice);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel22);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuTextBoxMedicineName);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuTextBoxMedicineID);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel23);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel24);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(42, 47);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(521, 395);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 41;
            this.bunifuToolTip1.SetToolTip(this.bunifuShadowPanel2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuShadowPanel2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuShadowPanel2, "");
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(41, 240);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(55, 17);
            this.bunifuLabel1.TabIndex = 33;
            this.bunifuLabel1.Text = "Số lượng";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuTextBoxQuantity
            // 
            this.bunifuTextBoxQuantity.AcceptsReturn = false;
            this.bunifuTextBoxQuantity.AcceptsTab = false;
            this.bunifuTextBoxQuantity.AnimationSpeed = 200;
            this.bunifuTextBoxQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxQuantity.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxQuantity.BackgroundImage")));
            this.bunifuTextBoxQuantity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxQuantity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxQuantity.BorderRadius = 10;
            this.bunifuTextBoxQuantity.BorderThickness = 1;
            this.bunifuTextBoxQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxQuantity.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuTextBoxQuantity.DefaultText = "";
            this.bunifuTextBoxQuantity.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxQuantity.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxQuantity.HideSelection = true;
            this.bunifuTextBoxQuantity.IconLeft = null;
            this.bunifuTextBoxQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxQuantity.IconPadding = 10;
            this.bunifuTextBoxQuantity.IconRight = null;
            this.bunifuTextBoxQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxQuantity.Lines = new string[0];
            this.bunifuTextBoxQuantity.Location = new System.Drawing.Point(155, 226);
            this.bunifuTextBoxQuantity.MaxLength = 32767;
            this.bunifuTextBoxQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxQuantity.Modified = false;
            this.bunifuTextBoxQuantity.Multiline = false;
            this.bunifuTextBoxQuantity.Name = "bunifuTextBoxQuantity";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxQuantity.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxQuantity.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxQuantity.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxQuantity.OnIdleState = stateProperties4;
            this.bunifuTextBoxQuantity.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.bunifuTextBoxQuantity.PasswordChar = '\0';
            this.bunifuTextBoxQuantity.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxQuantity.PlaceholderText = "Nhập số lượng thuốc";
            this.bunifuTextBoxQuantity.ReadOnly = false;
            this.bunifuTextBoxQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxQuantity.SelectedText = "";
            this.bunifuTextBoxQuantity.SelectionLength = 0;
            this.bunifuTextBoxQuantity.SelectionStart = 0;
            this.bunifuTextBoxQuantity.ShortcutsEnabled = true;
            this.bunifuTextBoxQuantity.Size = new System.Drawing.Size(291, 40);
            this.bunifuTextBoxQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxQuantity.TabIndex = 32;
            this.bunifuTextBoxQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxQuantity.TextMarginBottom = 0;
            this.bunifuTextBoxQuantity.TextMarginLeft = 3;
            this.bunifuTextBoxQuantity.TextMarginTop = 0;
            this.bunifuTextBoxQuantity.TextPlaceholder = "Nhập số lượng thuốc";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxQuantity, "Chỉ cho phép nhập số");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxQuantity, global::DO_AN_CUA_HAN.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxQuantity, "Warning");
            this.bunifuTextBoxQuantity.UseSystemPasswordChar = false;
            this.bunifuTextBoxQuantity.WordWrap = true;
            this.bunifuTextBoxQuantity.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.bunifuTextBoxQuantity_KeyPress);
            // 
            // bunifuButtonClose
            // 
            this.bunifuButtonClose.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButtonClose.AllowAnimations = true;
            this.bunifuButtonClose.AllowMouseEffects = true;
            this.bunifuButtonClose.AllowToggling = false;
            this.bunifuButtonClose.AnimationSpeed = 200;
            this.bunifuButtonClose.AutoGenerateColors = false;
            this.bunifuButtonClose.AutoRoundBorders = false;
            this.bunifuButtonClose.AutoSizeLeftIcon = true;
            this.bunifuButtonClose.AutoSizeRightIcon = true;
            this.bunifuButtonClose.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonClose.BackgroundImage")));
            this.bunifuButtonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.ButtonText = "Thoát";
            this.bunifuButtonClose.ButtonTextMarginLeft = 0;
            this.bunifuButtonClose.ColorContrastOnClick = 45;
            this.bunifuButtonClose.ColorContrastOnHover = 45;
            this.bunifuButtonClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonClose.CustomizableEdges = borderEdges1;
            this.bunifuButtonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonClose.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuButtonClose.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButtonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonClose.IconMarginLeft = 11;
            this.bunifuButtonClose.IconPadding = 10;
            this.bunifuButtonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonClose.IconSize = 25;
            this.bunifuButtonClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonClose.IdleBorderRadius = 15;
            this.bunifuButtonClose.IdleBorderThickness = 1;
            this.bunifuButtonClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonClose.IdleIconLeftImage = null;
            this.bunifuButtonClose.IdleIconRightImage = null;
            this.bunifuButtonClose.IndicateFocus = false;
            this.bunifuButtonClose.Location = new System.Drawing.Point(422, 344);
            this.bunifuButtonClose.Name = "bunifuButtonClose";
            this.bunifuButtonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonClose.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonClose.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonClose.OnDisabledState.IconRightImage = null;
            this.bunifuButtonClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonClose.onHoverState.BorderRadius = 15;
            this.bunifuButtonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.onHoverState.BorderThickness = 1;
            this.bunifuButtonClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.bunifuButtonClose.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButtonClose.onHoverState.IconLeftImage = null;
            this.bunifuButtonClose.onHoverState.IconRightImage = null;
            this.bunifuButtonClose.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonClose.OnIdleState.BorderRadius = 15;
            this.bunifuButtonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnIdleState.BorderThickness = 1;
            this.bunifuButtonClose.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonClose.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButtonClose.OnIdleState.IconLeftImage = null;
            this.bunifuButtonClose.OnIdleState.IconRightImage = null;
            this.bunifuButtonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonClose.OnPressedState.BorderRadius = 15;
            this.bunifuButtonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonClose.OnPressedState.BorderThickness = 1;
            this.bunifuButtonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonClose.OnPressedState.IconLeftImage = null;
            this.bunifuButtonClose.OnPressedState.IconRightImage = null;
            this.bunifuButtonClose.Size = new System.Drawing.Size(63, 37);
            this.bunifuButtonClose.TabIndex = 31;
            this.bunifuButtonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonClose.TextMarginLeft = 0;
            this.bunifuButtonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButtonClose, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButtonClose, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButtonClose, "");
            this.bunifuButtonClose.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonClose.Click += new System.EventHandler(this.bunifuButtonClose_Click);
            // 
            // bunifuButtonOK
            // 
            this.bunifuButtonOK.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButtonOK.AllowAnimations = true;
            this.bunifuButtonOK.AllowMouseEffects = true;
            this.bunifuButtonOK.AllowToggling = false;
            this.bunifuButtonOK.AnimationSpeed = 200;
            this.bunifuButtonOK.AutoGenerateColors = false;
            this.bunifuButtonOK.AutoRoundBorders = false;
            this.bunifuButtonOK.AutoSizeLeftIcon = true;
            this.bunifuButtonOK.AutoSizeRightIcon = true;
            this.bunifuButtonOK.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonOK.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonOK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonOK.BackgroundImage")));
            this.bunifuButtonOK.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonOK.ButtonText = "Đồng ý";
            this.bunifuButtonOK.ButtonTextMarginLeft = 0;
            this.bunifuButtonOK.ColorContrastOnClick = 45;
            this.bunifuButtonOK.ColorContrastOnHover = 45;
            this.bunifuButtonOK.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonOK.CustomizableEdges = borderEdges2;
            this.bunifuButtonOK.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonOK.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonOK.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonOK.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonOK.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonOK.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuButtonOK.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButtonOK.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonOK.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonOK.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonOK.IconMarginLeft = 11;
            this.bunifuButtonOK.IconPadding = 10;
            this.bunifuButtonOK.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonOK.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonOK.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonOK.IconSize = 25;
            this.bunifuButtonOK.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonOK.IdleBorderRadius = 15;
            this.bunifuButtonOK.IdleBorderThickness = 1;
            this.bunifuButtonOK.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonOK.IdleIconLeftImage = null;
            this.bunifuButtonOK.IdleIconRightImage = null;
            this.bunifuButtonOK.IndicateFocus = false;
            this.bunifuButtonOK.Location = new System.Drawing.Point(330, 344);
            this.bunifuButtonOK.Name = "bunifuButtonOK";
            this.bunifuButtonOK.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonOK.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonOK.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonOK.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonOK.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonOK.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonOK.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonOK.OnDisabledState.IconRightImage = null;
            this.bunifuButtonOK.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonOK.onHoverState.BorderRadius = 15;
            this.bunifuButtonOK.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonOK.onHoverState.BorderThickness = 1;
            this.bunifuButtonOK.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.bunifuButtonOK.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButtonOK.onHoverState.IconLeftImage = null;
            this.bunifuButtonOK.onHoverState.IconRightImage = null;
            this.bunifuButtonOK.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonOK.OnIdleState.BorderRadius = 15;
            this.bunifuButtonOK.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonOK.OnIdleState.BorderThickness = 1;
            this.bunifuButtonOK.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButtonOK.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButtonOK.OnIdleState.IconLeftImage = null;
            this.bunifuButtonOK.OnIdleState.IconRightImage = null;
            this.bunifuButtonOK.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonOK.OnPressedState.BorderRadius = 15;
            this.bunifuButtonOK.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonOK.OnPressedState.BorderThickness = 1;
            this.bunifuButtonOK.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonOK.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonOK.OnPressedState.IconLeftImage = null;
            this.bunifuButtonOK.OnPressedState.IconRightImage = null;
            this.bunifuButtonOK.Size = new System.Drawing.Size(63, 37);
            this.bunifuButtonOK.TabIndex = 30;
            this.bunifuButtonOK.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonOK.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonOK.TextMarginLeft = 0;
            this.bunifuButtonOK.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButtonOK, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButtonOK, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButtonOK, "");
            this.bunifuButtonOK.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonOK.Click += new System.EventHandler(this.bunifuButtonOK_Click);
            // 
            // bunifuLabel18
            // 
            this.bunifuLabel18.AllowParentOverrides = false;
            this.bunifuLabel18.AutoEllipsis = false;
            this.bunifuLabel18.CursorType = null;
            this.bunifuLabel18.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel18.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel18.Location = new System.Drawing.Point(48, 307);
            this.bunifuLabel18.Name = "bunifuLabel18";
            this.bunifuLabel18.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel18.Size = new System.Drawing.Size(48, 17);
            this.bunifuLabel18.TabIndex = 27;
            this.bunifuLabel18.Text = "Đơn giá";
            this.bunifuLabel18.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel18.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel18, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel18, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel18, "");
            // 
            // bunifuTextBoxPrice
            // 
            this.bunifuTextBoxPrice.AcceptsReturn = false;
            this.bunifuTextBoxPrice.AcceptsTab = false;
            this.bunifuTextBoxPrice.AnimationSpeed = 200;
            this.bunifuTextBoxPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPrice.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPrice.BackgroundImage")));
            this.bunifuTextBoxPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPrice.BorderRadius = 10;
            this.bunifuTextBoxPrice.BorderThickness = 1;
            this.bunifuTextBoxPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPrice.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuTextBoxPrice.DefaultText = "";
            this.bunifuTextBoxPrice.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPrice.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxPrice.HideSelection = true;
            this.bunifuTextBoxPrice.IconLeft = null;
            this.bunifuTextBoxPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPrice.IconPadding = 10;
            this.bunifuTextBoxPrice.IconRight = null;
            this.bunifuTextBoxPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPrice.Lines = new string[0];
            this.bunifuTextBoxPrice.Location = new System.Drawing.Point(155, 294);
            this.bunifuTextBoxPrice.MaxLength = 32767;
            this.bunifuTextBoxPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPrice.Modified = false;
            this.bunifuTextBoxPrice.Multiline = false;
            this.bunifuTextBoxPrice.Name = "bunifuTextBoxPrice";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPrice.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPrice.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPrice.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPrice.OnIdleState = stateProperties8;
            this.bunifuTextBoxPrice.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.bunifuTextBoxPrice.PasswordChar = '\0';
            this.bunifuTextBoxPrice.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxPrice.PlaceholderText = "Nhập đơn giá";
            this.bunifuTextBoxPrice.ReadOnly = false;
            this.bunifuTextBoxPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPrice.SelectedText = "";
            this.bunifuTextBoxPrice.SelectionLength = 0;
            this.bunifuTextBoxPrice.SelectionStart = 0;
            this.bunifuTextBoxPrice.ShortcutsEnabled = true;
            this.bunifuTextBoxPrice.Size = new System.Drawing.Size(291, 40);
            this.bunifuTextBoxPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxPrice.TabIndex = 26;
            this.bunifuTextBoxPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxPrice.TextMarginBottom = 0;
            this.bunifuTextBoxPrice.TextMarginLeft = 3;
            this.bunifuTextBoxPrice.TextMarginTop = 0;
            this.bunifuTextBoxPrice.TextPlaceholder = "Nhập đơn giá";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxPrice, "Chỉ cho phép nhập số");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxPrice, global::DO_AN_CUA_HAN.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxPrice, "Warning");
            this.bunifuTextBoxPrice.UseSystemPasswordChar = false;
            this.bunifuTextBoxPrice.WordWrap = true;
            // 
            // bunifuLabel22
            // 
            this.bunifuLabel22.AllowParentOverrides = false;
            this.bunifuLabel22.AutoEllipsis = false;
            this.bunifuLabel22.CursorType = null;
            this.bunifuLabel22.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel22.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel22.Location = new System.Drawing.Point(41, 172);
            this.bunifuLabel22.Name = "bunifuLabel22";
            this.bunifuLabel22.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel22.Size = new System.Drawing.Size(63, 17);
            this.bunifuLabel22.TabIndex = 16;
            this.bunifuLabel22.Text = "Tên thuốc";
            this.bunifuLabel22.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel22.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel22, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel22, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel22, "");
            // 
            // bunifuTextBoxMedicineName
            // 
            this.bunifuTextBoxMedicineName.AcceptsReturn = false;
            this.bunifuTextBoxMedicineName.AcceptsTab = false;
            this.bunifuTextBoxMedicineName.AnimationSpeed = 200;
            this.bunifuTextBoxMedicineName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxMedicineName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxMedicineName.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxMedicineName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxMedicineName.BackgroundImage")));
            this.bunifuTextBoxMedicineName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxMedicineName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxMedicineName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxMedicineName.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxMedicineName.BorderRadius = 10;
            this.bunifuTextBoxMedicineName.BorderThickness = 1;
            this.bunifuTextBoxMedicineName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxMedicineName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMedicineName.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuTextBoxMedicineName.DefaultText = "";
            this.bunifuTextBoxMedicineName.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxMedicineName.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxMedicineName.HideSelection = true;
            this.bunifuTextBoxMedicineName.IconLeft = null;
            this.bunifuTextBoxMedicineName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMedicineName.IconPadding = 10;
            this.bunifuTextBoxMedicineName.IconRight = null;
            this.bunifuTextBoxMedicineName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMedicineName.Lines = new string[0];
            this.bunifuTextBoxMedicineName.Location = new System.Drawing.Point(155, 158);
            this.bunifuTextBoxMedicineName.MaxLength = 32767;
            this.bunifuTextBoxMedicineName.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxMedicineName.Modified = false;
            this.bunifuTextBoxMedicineName.Multiline = false;
            this.bunifuTextBoxMedicineName.Name = "bunifuTextBoxMedicineName";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMedicineName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxMedicineName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMedicineName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMedicineName.OnIdleState = stateProperties12;
            this.bunifuTextBoxMedicineName.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.bunifuTextBoxMedicineName.PasswordChar = '\0';
            this.bunifuTextBoxMedicineName.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxMedicineName.PlaceholderText = "Nhập tên thuốc";
            this.bunifuTextBoxMedicineName.ReadOnly = false;
            this.bunifuTextBoxMedicineName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxMedicineName.SelectedText = "";
            this.bunifuTextBoxMedicineName.SelectionLength = 0;
            this.bunifuTextBoxMedicineName.SelectionStart = 0;
            this.bunifuTextBoxMedicineName.ShortcutsEnabled = true;
            this.bunifuTextBoxMedicineName.Size = new System.Drawing.Size(291, 40);
            this.bunifuTextBoxMedicineName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxMedicineName.TabIndex = 13;
            this.bunifuTextBoxMedicineName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxMedicineName.TextMarginBottom = 0;
            this.bunifuTextBoxMedicineName.TextMarginLeft = 3;
            this.bunifuTextBoxMedicineName.TextMarginTop = 0;
            this.bunifuTextBoxMedicineName.TextPlaceholder = "Nhập tên thuốc";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxMedicineName, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxMedicineName, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxMedicineName, "Warning");
            this.bunifuTextBoxMedicineName.UseSystemPasswordChar = false;
            this.bunifuTextBoxMedicineName.WordWrap = true;
            this.bunifuTextBoxMedicineName.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.bunifuTextBoxMedicineName_KeyPress);
            // 
            // bunifuTextBoxMedicineID
            // 
            this.bunifuTextBoxMedicineID.AcceptsReturn = false;
            this.bunifuTextBoxMedicineID.AcceptsTab = false;
            this.bunifuTextBoxMedicineID.AnimationSpeed = 200;
            this.bunifuTextBoxMedicineID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxMedicineID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxMedicineID.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxMedicineID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxMedicineID.BackgroundImage")));
            this.bunifuTextBoxMedicineID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxMedicineID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxMedicineID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxMedicineID.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxMedicineID.BorderRadius = 20;
            this.bunifuTextBoxMedicineID.BorderThickness = 1;
            this.bunifuTextBoxMedicineID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxMedicineID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMedicineID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuTextBoxMedicineID.DefaultText = "";
            this.bunifuTextBoxMedicineID.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxMedicineID.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxMedicineID.HideSelection = true;
            this.bunifuTextBoxMedicineID.IconLeft = null;
            this.bunifuTextBoxMedicineID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMedicineID.IconPadding = 10;
            this.bunifuTextBoxMedicineID.IconRight = null;
            this.bunifuTextBoxMedicineID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxMedicineID.Lines = new string[0];
            this.bunifuTextBoxMedicineID.Location = new System.Drawing.Point(155, 94);
            this.bunifuTextBoxMedicineID.MaxLength = 32767;
            this.bunifuTextBoxMedicineID.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxMedicineID.Modified = false;
            this.bunifuTextBoxMedicineID.Multiline = false;
            this.bunifuTextBoxMedicineID.Name = "bunifuTextBoxMedicineID";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMedicineID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxMedicineID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMedicineID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxMedicineID.OnIdleState = stateProperties16;
            this.bunifuTextBoxMedicineID.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.bunifuTextBoxMedicineID.PasswordChar = '\0';
            this.bunifuTextBoxMedicineID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxMedicineID.PlaceholderText = "Nhập mã thuốc";
            this.bunifuTextBoxMedicineID.ReadOnly = true;
            this.bunifuTextBoxMedicineID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxMedicineID.SelectedText = "";
            this.bunifuTextBoxMedicineID.SelectionLength = 0;
            this.bunifuTextBoxMedicineID.SelectionStart = 0;
            this.bunifuTextBoxMedicineID.ShortcutsEnabled = true;
            this.bunifuTextBoxMedicineID.Size = new System.Drawing.Size(291, 40);
            this.bunifuTextBoxMedicineID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxMedicineID.TabIndex = 12;
            this.bunifuTextBoxMedicineID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxMedicineID.TextMarginBottom = 0;
            this.bunifuTextBoxMedicineID.TextMarginLeft = 3;
            this.bunifuTextBoxMedicineID.TextMarginTop = 0;
            this.bunifuTextBoxMedicineID.TextPlaceholder = "Nhập mã thuốc";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxMedicineID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxMedicineID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxMedicineID, "");
            this.bunifuTextBoxMedicineID.UseSystemPasswordChar = false;
            this.bunifuTextBoxMedicineID.WordWrap = true;
            // 
            // bunifuLabel23
            // 
            this.bunifuLabel23.AllowParentOverrides = false;
            this.bunifuLabel23.AutoEllipsis = false;
            this.bunifuLabel23.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel23.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel23.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel23.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel23.Location = new System.Drawing.Point(41, 108);
            this.bunifuLabel23.Name = "bunifuLabel23";
            this.bunifuLabel23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel23.Size = new System.Drawing.Size(58, 17);
            this.bunifuLabel23.TabIndex = 2;
            this.bunifuLabel23.Text = "Mã thuốc";
            this.bunifuLabel23.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel23.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel23, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel23, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel23, "");
            // 
            // bunifuLabel24
            // 
            this.bunifuLabel24.AllowParentOverrides = false;
            this.bunifuLabel24.AutoEllipsis = false;
            this.bunifuLabel24.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel24.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel24.Font = new System.Drawing.Font("Cambria", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel24.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel24.Location = new System.Drawing.Point(213, 31);
            this.bunifuLabel24.Name = "bunifuLabel24";
            this.bunifuLabel24.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel24.Size = new System.Drawing.Size(79, 28);
            this.bunifuLabel24.TabIndex = 1;
            this.bunifuLabel24.Text = "THUỐC";
            this.bunifuLabel24.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel24.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel24, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel24, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel24, "");
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 47;
            this.bunifuPictureBox1.Image = global::DO_AN_CUA_HAN.Properties.Resources._5413809_effects_removebg_preview;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(112, 3);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(95, 95);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 34;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(221)))), ((int)(((byte)(85)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.DimGray;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // FormMedicineDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(616, 491);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "FormMedicineDetail";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormMedicineDetail";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonOK;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel18;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPrice;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel22;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxMedicineName;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxMedicineID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel23;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel24;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxQuantity;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
    }
}