namespace DO_AN_CUA_HAN.View
{
    partial class FormMainDeptMajor
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMainDeptMajor));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonDepartmentAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonDepartmentDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonDepartmentEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox9 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonMajorAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox7 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonMajorDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox8 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonMajorEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuDataGridViewMajor = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuDataGridViewDeparment = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewMajor)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewDeparment)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 30;
            this.bunifuShadowPanel1.BorderThickness = 0;
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonDepartmentAdd);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonDepartmentDelete);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonDepartmentEdit);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox9);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonMajorAdd);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox7);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonMajorDelete);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox8);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonMajorEdit);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDataGridViewMajor);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDataGridViewDeparment);
            this.bunifuShadowPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(236)))), ((int)(((byte)(210)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(182)))), ((int)(((byte)(189)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 0;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(989, 792);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 6;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.pictureBox1.Image = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_interface_plus_user_business_flat_line_filled_icon_vector_19177343_removebg_preview__1_;
            this.pictureBox1.Location = new System.Drawing.Point(340, 700);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(43, 43);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 37;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuButtonDepartmentAdd
            // 
            this.bunifuButtonDepartmentAdd.AllowAnimations = true;
            this.bunifuButtonDepartmentAdd.AllowMouseEffects = true;
            this.bunifuButtonDepartmentAdd.AllowToggling = false;
            this.bunifuButtonDepartmentAdd.AnimationSpeed = 200;
            this.bunifuButtonDepartmentAdd.AutoGenerateColors = false;
            this.bunifuButtonDepartmentAdd.AutoRoundBorders = false;
            this.bunifuButtonDepartmentAdd.AutoSizeLeftIcon = true;
            this.bunifuButtonDepartmentAdd.AutoSizeRightIcon = true;
            this.bunifuButtonDepartmentAdd.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDepartmentAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDepartmentAdd.BackgroundImage")));
            this.bunifuButtonDepartmentAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonDepartmentAdd.ButtonText = "         Thêm mới";
            this.bunifuButtonDepartmentAdd.ButtonTextMarginLeft = 0;
            this.bunifuButtonDepartmentAdd.ColorContrastOnClick = 45;
            this.bunifuButtonDepartmentAdd.ColorContrastOnHover = 45;
            this.bunifuButtonDepartmentAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonDepartmentAdd.CustomizableEdges = borderEdges1;
            this.bunifuButtonDepartmentAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDepartmentAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonDepartmentAdd.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonDepartmentAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDepartmentAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonDepartmentAdd.IconMarginLeft = 11;
            this.bunifuButtonDepartmentAdd.IconPadding = 10;
            this.bunifuButtonDepartmentAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDepartmentAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonDepartmentAdd.IconSize = 25;
            this.bunifuButtonDepartmentAdd.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonDepartmentAdd.IdleBorderRadius = 15;
            this.bunifuButtonDepartmentAdd.IdleBorderThickness = 2;
            this.bunifuButtonDepartmentAdd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentAdd.IdleIconLeftImage = null;
            this.bunifuButtonDepartmentAdd.IdleIconRightImage = null;
            this.bunifuButtonDepartmentAdd.IndicateFocus = false;
            this.bunifuButtonDepartmentAdd.Location = new System.Drawing.Point(334, 696);
            this.bunifuButtonDepartmentAdd.Name = "bunifuButtonDepartmentAdd";
            this.bunifuButtonDepartmentAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentAdd.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonDepartmentAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentAdd.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonDepartmentAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentAdd.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDepartmentAdd.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDepartmentAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentAdd.onHoverState.BorderRadius = 15;
            this.bunifuButtonDepartmentAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentAdd.onHoverState.BorderThickness = 2;
            this.bunifuButtonDepartmentAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentAdd.onHoverState.IconLeftImage = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_flat_isometric_illustration_concept_symbol_of_the_best_7885579_removebg_preview;
            this.bunifuButtonDepartmentAdd.onHoverState.IconRightImage = null;
            this.bunifuButtonDepartmentAdd.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonDepartmentAdd.OnIdleState.BorderRadius = 15;
            this.bunifuButtonDepartmentAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonDepartmentAdd.OnIdleState.BorderThickness = 2;
            this.bunifuButtonDepartmentAdd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentAdd.OnIdleState.IconLeftImage = null;
            this.bunifuButtonDepartmentAdd.OnIdleState.IconRightImage = null;
            this.bunifuButtonDepartmentAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentAdd.OnPressedState.BorderRadius = 15;
            this.bunifuButtonDepartmentAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentAdd.OnPressedState.BorderThickness = 2;
            this.bunifuButtonDepartmentAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentAdd.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDepartmentAdd.OnPressedState.IconRightImage = null;
            this.bunifuButtonDepartmentAdd.Size = new System.Drawing.Size(127, 51);
            this.bunifuButtonDepartmentAdd.TabIndex = 36;
            this.bunifuButtonDepartmentAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonDepartmentAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDepartmentAdd.TextMarginLeft = 0;
            this.bunifuButtonDepartmentAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDepartmentAdd.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonDepartmentAdd.Click += new System.EventHandler(this.bunifuButtonDeparmentAdd_Click);
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.pictureBox2.Image = global::DO_AN_CUA_HAN.Properties.Resources.z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview;
            this.pictureBox2.Location = new System.Drawing.Point(47, 700);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(43, 43);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 35;
            this.pictureBox2.TabStop = false;
            // 
            // bunifuButtonDepartmentDelete
            // 
            this.bunifuButtonDepartmentDelete.AllowAnimations = true;
            this.bunifuButtonDepartmentDelete.AllowMouseEffects = true;
            this.bunifuButtonDepartmentDelete.AllowToggling = false;
            this.bunifuButtonDepartmentDelete.AnimationSpeed = 200;
            this.bunifuButtonDepartmentDelete.AutoGenerateColors = false;
            this.bunifuButtonDepartmentDelete.AutoRoundBorders = false;
            this.bunifuButtonDepartmentDelete.AutoSizeLeftIcon = true;
            this.bunifuButtonDepartmentDelete.AutoSizeRightIcon = true;
            this.bunifuButtonDepartmentDelete.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDepartmentDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDepartmentDelete.BackgroundImage")));
            this.bunifuButtonDepartmentDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonDepartmentDelete.ButtonText = "      Xóa";
            this.bunifuButtonDepartmentDelete.ButtonTextMarginLeft = 0;
            this.bunifuButtonDepartmentDelete.ColorContrastOnClick = 45;
            this.bunifuButtonDepartmentDelete.ColorContrastOnHover = 45;
            this.bunifuButtonDepartmentDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonDepartmentDelete.CustomizableEdges = borderEdges2;
            this.bunifuButtonDepartmentDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDepartmentDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonDepartmentDelete.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonDepartmentDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDepartmentDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonDepartmentDelete.IconMarginLeft = 11;
            this.bunifuButtonDepartmentDelete.IconPadding = 10;
            this.bunifuButtonDepartmentDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDepartmentDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonDepartmentDelete.IconSize = 25;
            this.bunifuButtonDepartmentDelete.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonDepartmentDelete.IdleBorderRadius = 15;
            this.bunifuButtonDepartmentDelete.IdleBorderThickness = 2;
            this.bunifuButtonDepartmentDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentDelete.IdleIconLeftImage = null;
            this.bunifuButtonDepartmentDelete.IdleIconRightImage = null;
            this.bunifuButtonDepartmentDelete.IndicateFocus = false;
            this.bunifuButtonDepartmentDelete.Location = new System.Drawing.Point(40, 696);
            this.bunifuButtonDepartmentDelete.Name = "bunifuButtonDepartmentDelete";
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonDepartmentDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentDelete.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentDelete.onHoverState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.onHoverState.BorderThickness = 2;
            this.bunifuButtonDepartmentDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentDelete.onHoverState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.onHoverState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonDepartmentDelete.OnIdleState.BorderThickness = 2;
            this.bunifuButtonDepartmentDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentDelete.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentDelete.OnIdleState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.OnIdleState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderRadius = 15;
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentDelete.OnPressedState.BorderThickness = 2;
            this.bunifuButtonDepartmentDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentDelete.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDepartmentDelete.OnPressedState.IconRightImage = null;
            this.bunifuButtonDepartmentDelete.Size = new System.Drawing.Size(127, 51);
            this.bunifuButtonDepartmentDelete.TabIndex = 34;
            this.bunifuButtonDepartmentDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonDepartmentDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDepartmentDelete.TextMarginLeft = 0;
            this.bunifuButtonDepartmentDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDepartmentDelete.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonDepartmentDelete.Click += new System.EventHandler(this.bunifuButtonDepartmentDelete_Click);
            // 
            // pictureBox3
            // 
            this.pictureBox3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.pictureBox3.Image = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_removebg_preview;
            this.pictureBox3.Location = new System.Drawing.Point(189, 700);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(43, 43);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 33;
            this.pictureBox3.TabStop = false;
            // 
            // bunifuButtonDepartmentEdit
            // 
            this.bunifuButtonDepartmentEdit.AllowAnimations = true;
            this.bunifuButtonDepartmentEdit.AllowMouseEffects = true;
            this.bunifuButtonDepartmentEdit.AllowToggling = false;
            this.bunifuButtonDepartmentEdit.AnimationSpeed = 200;
            this.bunifuButtonDepartmentEdit.AutoGenerateColors = false;
            this.bunifuButtonDepartmentEdit.AutoRoundBorders = false;
            this.bunifuButtonDepartmentEdit.AutoSizeLeftIcon = true;
            this.bunifuButtonDepartmentEdit.AutoSizeRightIcon = true;
            this.bunifuButtonDepartmentEdit.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonDepartmentEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonDepartmentEdit.BackgroundImage")));
            this.bunifuButtonDepartmentEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonDepartmentEdit.ButtonText = "         Thay đổi";
            this.bunifuButtonDepartmentEdit.ButtonTextMarginLeft = 0;
            this.bunifuButtonDepartmentEdit.ColorContrastOnClick = 45;
            this.bunifuButtonDepartmentEdit.ColorContrastOnHover = 45;
            this.bunifuButtonDepartmentEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonDepartmentEdit.CustomizableEdges = borderEdges3;
            this.bunifuButtonDepartmentEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonDepartmentEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonDepartmentEdit.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonDepartmentEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonDepartmentEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonDepartmentEdit.IconMarginLeft = 11;
            this.bunifuButtonDepartmentEdit.IconPadding = 10;
            this.bunifuButtonDepartmentEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonDepartmentEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonDepartmentEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonDepartmentEdit.IconSize = 25;
            this.bunifuButtonDepartmentEdit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonDepartmentEdit.IdleBorderRadius = 15;
            this.bunifuButtonDepartmentEdit.IdleBorderThickness = 2;
            this.bunifuButtonDepartmentEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentEdit.IdleIconLeftImage = null;
            this.bunifuButtonDepartmentEdit.IdleIconRightImage = null;
            this.bunifuButtonDepartmentEdit.IndicateFocus = false;
            this.bunifuButtonDepartmentEdit.Location = new System.Drawing.Point(187, 696);
            this.bunifuButtonDepartmentEdit.Name = "bunifuButtonDepartmentEdit";
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonDepartmentEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonDepartmentEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonDepartmentEdit.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.OnDisabledState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentEdit.onHoverState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.onHoverState.BorderThickness = 2;
            this.bunifuButtonDepartmentEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonDepartmentEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentEdit.onHoverState.IconLeftImage = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_flat_isometric_illustration_concept_symbol_of_the_best_7885579_removebg_preview;
            this.bunifuButtonDepartmentEdit.onHoverState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonDepartmentEdit.OnIdleState.BorderThickness = 2;
            this.bunifuButtonDepartmentEdit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonDepartmentEdit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonDepartmentEdit.OnIdleState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.OnIdleState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderRadius = 15;
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonDepartmentEdit.OnPressedState.BorderThickness = 2;
            this.bunifuButtonDepartmentEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonDepartmentEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonDepartmentEdit.OnPressedState.IconLeftImage = null;
            this.bunifuButtonDepartmentEdit.OnPressedState.IconRightImage = null;
            this.bunifuButtonDepartmentEdit.Size = new System.Drawing.Size(127, 51);
            this.bunifuButtonDepartmentEdit.TabIndex = 32;
            this.bunifuButtonDepartmentEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonDepartmentEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonDepartmentEdit.TextMarginLeft = 0;
            this.bunifuButtonDepartmentEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonDepartmentEdit.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonDepartmentDelete.Click += new System.EventHandler(this.bunifuButtonDepartmentDelete_Click);
            // 
            // pictureBox9
            // 
            this.pictureBox9.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.pictureBox9.Image = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_interface_plus_user_business_flat_line_filled_icon_vector_19177343_removebg_preview__1_;
            this.pictureBox9.Location = new System.Drawing.Point(818, 704);
            this.pictureBox9.Name = "pictureBox9";
            this.pictureBox9.Size = new System.Drawing.Size(43, 43);
            this.pictureBox9.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox9.TabIndex = 31;
            this.pictureBox9.TabStop = false;
            // 
            // bunifuButtonMajorAdd
            // 
            this.bunifuButtonMajorAdd.AllowAnimations = true;
            this.bunifuButtonMajorAdd.AllowMouseEffects = true;
            this.bunifuButtonMajorAdd.AllowToggling = false;
            this.bunifuButtonMajorAdd.AnimationSpeed = 200;
            this.bunifuButtonMajorAdd.AutoGenerateColors = false;
            this.bunifuButtonMajorAdd.AutoRoundBorders = false;
            this.bunifuButtonMajorAdd.AutoSizeLeftIcon = true;
            this.bunifuButtonMajorAdd.AutoSizeRightIcon = true;
            this.bunifuButtonMajorAdd.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMajorAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMajorAdd.BackgroundImage")));
            this.bunifuButtonMajorAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonMajorAdd.ButtonText = "         Thêm mới";
            this.bunifuButtonMajorAdd.ButtonTextMarginLeft = 0;
            this.bunifuButtonMajorAdd.ColorContrastOnClick = 45;
            this.bunifuButtonMajorAdd.ColorContrastOnHover = 45;
            this.bunifuButtonMajorAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButtonMajorAdd.CustomizableEdges = borderEdges4;
            this.bunifuButtonMajorAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMajorAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMajorAdd.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMajorAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMajorAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMajorAdd.IconMarginLeft = 11;
            this.bunifuButtonMajorAdd.IconPadding = 10;
            this.bunifuButtonMajorAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMajorAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMajorAdd.IconSize = 25;
            this.bunifuButtonMajorAdd.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonMajorAdd.IdleBorderRadius = 15;
            this.bunifuButtonMajorAdd.IdleBorderThickness = 2;
            this.bunifuButtonMajorAdd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorAdd.IdleIconLeftImage = null;
            this.bunifuButtonMajorAdd.IdleIconRightImage = null;
            this.bunifuButtonMajorAdd.IndicateFocus = false;
            this.bunifuButtonMajorAdd.Location = new System.Drawing.Point(812, 700);
            this.bunifuButtonMajorAdd.Name = "bunifuButtonMajorAdd";
            this.bunifuButtonMajorAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorAdd.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonMajorAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorAdd.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMajorAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorAdd.onHoverState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.onHoverState.BorderThickness = 2;
            this.bunifuButtonMajorAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorAdd.onHoverState.IconLeftImage = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_flat_isometric_illustration_concept_symbol_of_the_best_7885579_removebg_preview;
            this.bunifuButtonMajorAdd.onHoverState.IconRightImage = null;
            this.bunifuButtonMajorAdd.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonMajorAdd.OnIdleState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonMajorAdd.OnIdleState.BorderThickness = 2;
            this.bunifuButtonMajorAdd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorAdd.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.OnIdleState.IconRightImage = null;
            this.bunifuButtonMajorAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorAdd.OnPressedState.BorderRadius = 15;
            this.bunifuButtonMajorAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorAdd.OnPressedState.BorderThickness = 2;
            this.bunifuButtonMajorAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorAdd.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMajorAdd.OnPressedState.IconRightImage = null;
            this.bunifuButtonMajorAdd.Size = new System.Drawing.Size(127, 51);
            this.bunifuButtonMajorAdd.TabIndex = 30;
            this.bunifuButtonMajorAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMajorAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMajorAdd.TextMarginLeft = 0;
            this.bunifuButtonMajorAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMajorAdd.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonMajorAdd.Click += new System.EventHandler(this.bunifuButtonMajorAdd_Click);
            // 
            // pictureBox7
            // 
            this.pictureBox7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.pictureBox7.Image = global::DO_AN_CUA_HAN.Properties.Resources.z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview;
            this.pictureBox7.Location = new System.Drawing.Point(525, 704);
            this.pictureBox7.Name = "pictureBox7";
            this.pictureBox7.Size = new System.Drawing.Size(43, 43);
            this.pictureBox7.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox7.TabIndex = 29;
            this.pictureBox7.TabStop = false;
            // 
            // bunifuButtonMajorDelete
            // 
            this.bunifuButtonMajorDelete.AllowAnimations = true;
            this.bunifuButtonMajorDelete.AllowMouseEffects = true;
            this.bunifuButtonMajorDelete.AllowToggling = false;
            this.bunifuButtonMajorDelete.AnimationSpeed = 200;
            this.bunifuButtonMajorDelete.AutoGenerateColors = false;
            this.bunifuButtonMajorDelete.AutoRoundBorders = false;
            this.bunifuButtonMajorDelete.AutoSizeLeftIcon = true;
            this.bunifuButtonMajorDelete.AutoSizeRightIcon = true;
            this.bunifuButtonMajorDelete.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMajorDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMajorDelete.BackgroundImage")));
            this.bunifuButtonMajorDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonMajorDelete.ButtonText = "      Xóa";
            this.bunifuButtonMajorDelete.ButtonTextMarginLeft = 0;
            this.bunifuButtonMajorDelete.ColorContrastOnClick = 45;
            this.bunifuButtonMajorDelete.ColorContrastOnHover = 45;
            this.bunifuButtonMajorDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButtonMajorDelete.CustomizableEdges = borderEdges5;
            this.bunifuButtonMajorDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMajorDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMajorDelete.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMajorDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMajorDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMajorDelete.IconMarginLeft = 11;
            this.bunifuButtonMajorDelete.IconPadding = 10;
            this.bunifuButtonMajorDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMajorDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMajorDelete.IconSize = 25;
            this.bunifuButtonMajorDelete.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonMajorDelete.IdleBorderRadius = 15;
            this.bunifuButtonMajorDelete.IdleBorderThickness = 2;
            this.bunifuButtonMajorDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorDelete.IdleIconLeftImage = null;
            this.bunifuButtonMajorDelete.IdleIconRightImage = null;
            this.bunifuButtonMajorDelete.IndicateFocus = false;
            this.bunifuButtonMajorDelete.Location = new System.Drawing.Point(518, 700);
            this.bunifuButtonMajorDelete.Name = "bunifuButtonMajorDelete";
            this.bunifuButtonMajorDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorDelete.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonMajorDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorDelete.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMajorDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorDelete.onHoverState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.onHoverState.BorderThickness = 2;
            this.bunifuButtonMajorDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorDelete.onHoverState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.onHoverState.IconRightImage = null;
            this.bunifuButtonMajorDelete.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonMajorDelete.OnIdleState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonMajorDelete.OnIdleState.BorderThickness = 2;
            this.bunifuButtonMajorDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorDelete.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorDelete.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.OnIdleState.IconRightImage = null;
            this.bunifuButtonMajorDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorDelete.OnPressedState.BorderRadius = 15;
            this.bunifuButtonMajorDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorDelete.OnPressedState.BorderThickness = 2;
            this.bunifuButtonMajorDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorDelete.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMajorDelete.OnPressedState.IconRightImage = null;
            this.bunifuButtonMajorDelete.Size = new System.Drawing.Size(127, 51);
            this.bunifuButtonMajorDelete.TabIndex = 28;
            this.bunifuButtonMajorDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMajorDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMajorDelete.TextMarginLeft = 0;
            this.bunifuButtonMajorDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMajorDelete.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonMajorDelete.Click += new System.EventHandler(this.bunifuButtonMajorDelete_Click);
            // 
            // pictureBox8
            // 
            this.pictureBox8.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.pictureBox8.Image = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_removebg_preview;
            this.pictureBox8.Location = new System.Drawing.Point(667, 704);
            this.pictureBox8.Name = "pictureBox8";
            this.pictureBox8.Size = new System.Drawing.Size(43, 43);
            this.pictureBox8.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox8.TabIndex = 27;
            this.pictureBox8.TabStop = false;
            // 
            // bunifuButtonMajorEdit
            // 
            this.bunifuButtonMajorEdit.AllowAnimations = true;
            this.bunifuButtonMajorEdit.AllowMouseEffects = true;
            this.bunifuButtonMajorEdit.AllowToggling = false;
            this.bunifuButtonMajorEdit.AnimationSpeed = 200;
            this.bunifuButtonMajorEdit.AutoGenerateColors = false;
            this.bunifuButtonMajorEdit.AutoRoundBorders = false;
            this.bunifuButtonMajorEdit.AutoSizeLeftIcon = true;
            this.bunifuButtonMajorEdit.AutoSizeRightIcon = true;
            this.bunifuButtonMajorEdit.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonMajorEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonMajorEdit.BackgroundImage")));
            this.bunifuButtonMajorEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonMajorEdit.ButtonText = "         Thay đổi";
            this.bunifuButtonMajorEdit.ButtonTextMarginLeft = 0;
            this.bunifuButtonMajorEdit.ColorContrastOnClick = 45;
            this.bunifuButtonMajorEdit.ColorContrastOnHover = 45;
            this.bunifuButtonMajorEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButtonMajorEdit.CustomizableEdges = borderEdges6;
            this.bunifuButtonMajorEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonMajorEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonMajorEdit.Font = new System.Drawing.Font("Times New Roman", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonMajorEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonMajorEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonMajorEdit.IconMarginLeft = 11;
            this.bunifuButtonMajorEdit.IconPadding = 10;
            this.bunifuButtonMajorEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonMajorEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonMajorEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonMajorEdit.IconSize = 25;
            this.bunifuButtonMajorEdit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonMajorEdit.IdleBorderRadius = 15;
            this.bunifuButtonMajorEdit.IdleBorderThickness = 2;
            this.bunifuButtonMajorEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorEdit.IdleIconLeftImage = null;
            this.bunifuButtonMajorEdit.IdleIconRightImage = null;
            this.bunifuButtonMajorEdit.IndicateFocus = false;
            this.bunifuButtonMajorEdit.Location = new System.Drawing.Point(665, 700);
            this.bunifuButtonMajorEdit.Name = "bunifuButtonMajorEdit";
            this.bunifuButtonMajorEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonMajorEdit.OnDisabledState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonMajorEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonMajorEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonMajorEdit.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.OnDisabledState.IconRightImage = null;
            this.bunifuButtonMajorEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorEdit.onHoverState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.onHoverState.BorderThickness = 2;
            this.bunifuButtonMajorEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonMajorEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorEdit.onHoverState.IconLeftImage = global::DO_AN_CUA_HAN.Properties.Resources.vecteezy_flat_isometric_illustration_concept_symbol_of_the_best_7885579_removebg_preview;
            this.bunifuButtonMajorEdit.onHoverState.IconRightImage = null;
            this.bunifuButtonMajorEdit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(113)))), ((int)(((byte)(103)))));
            this.bunifuButtonMajorEdit.OnIdleState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonMajorEdit.OnIdleState.BorderThickness = 2;
            this.bunifuButtonMajorEdit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuButtonMajorEdit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonMajorEdit.OnIdleState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.OnIdleState.IconRightImage = null;
            this.bunifuButtonMajorEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorEdit.OnPressedState.BorderRadius = 15;
            this.bunifuButtonMajorEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonMajorEdit.OnPressedState.BorderThickness = 2;
            this.bunifuButtonMajorEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonMajorEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonMajorEdit.OnPressedState.IconLeftImage = null;
            this.bunifuButtonMajorEdit.OnPressedState.IconRightImage = null;
            this.bunifuButtonMajorEdit.Size = new System.Drawing.Size(127, 51);
            this.bunifuButtonMajorEdit.TabIndex = 26;
            this.bunifuButtonMajorEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonMajorEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonMajorEdit.TextMarginLeft = 0;
            this.bunifuButtonMajorEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonMajorEdit.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonMajorEdit.Click += new System.EventHandler(this.bunifuButtonMajorEdit_Click);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Times New Roman", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(648, 62);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(183, 19);
            this.bunifuLabel4.TabIndex = 15;
            this.bunifuLabel4.Text = "Danh sách chuyên ngành:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Times New Roman", 13F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(203, 62);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(119, 19);
            this.bunifuLabel2.TabIndex = 13;
            this.bunifuLabel2.Text = "Danh sách khoa:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuDataGridViewMajor
            // 
            this.bunifuDataGridViewMajor.AllowCustomTheming = false;
            this.bunifuDataGridViewMajor.AllowUserToAddRows = false;
            this.bunifuDataGridViewMajor.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(196)))), ((int)(((byte)(206)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridViewMajor.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewMajor.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(217)))), ((int)(((byte)(198)))));
            this.bunifuDataGridViewMajor.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridViewMajor.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewMajor.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Crimson;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(16)))), ((int)(((byte)(48)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewMajor.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridViewMajor.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(196)))), ((int)(((byte)(206)))));
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            this.bunifuDataGridViewMajor.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.BackColor = System.Drawing.Color.Crimson;
            this.bunifuDataGridViewMajor.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(184)))), ((int)(((byte)(196)))));
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Crimson;
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(16)))), ((int)(((byte)(48)))));
            this.bunifuDataGridViewMajor.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.CurrentTheme.Name = null;
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(208)))), ((int)(((byte)(216)))));
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            this.bunifuDataGridViewMajor.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(208)))), ((int)(((byte)(216)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewMajor.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridViewMajor.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewMajor.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(184)))), ((int)(((byte)(196)))));
            this.bunifuDataGridViewMajor.HeaderBackColor = System.Drawing.Color.Crimson;
            this.bunifuDataGridViewMajor.HeaderBackColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewMajor.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewMajor.Location = new System.Drawing.Point(511, 107);
            this.bunifuDataGridViewMajor.Name = "bunifuDataGridViewMajor";
            this.bunifuDataGridViewMajor.RowHeadersVisible = false;
            this.bunifuDataGridViewMajor.RowTemplate.Height = 40;
            this.bunifuDataGridViewMajor.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewMajor.Size = new System.Drawing.Size(433, 550);
            this.bunifuDataGridViewMajor.TabIndex = 12;
            this.bunifuDataGridViewMajor.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Crimson;
            this.bunifuDataGridViewMajor.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridViewMajor_CellDoubleClick);
            // 
            // bunifuDataGridViewDeparment
            // 
            this.bunifuDataGridViewDeparment.AllowCustomTheming = false;
            this.bunifuDataGridViewDeparment.AllowUserToAddRows = false;
            this.bunifuDataGridViewDeparment.AllowUserToDeleteRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(196)))), ((int)(((byte)(206)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridViewDeparment.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewDeparment.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(217)))), ((int)(((byte)(198)))));
            this.bunifuDataGridViewDeparment.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridViewDeparment.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewDeparment.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.Crimson;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(16)))), ((int)(((byte)(48)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewDeparment.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridViewDeparment.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(196)))), ((int)(((byte)(206)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.BackColor = System.Drawing.Color.Crimson;
            this.bunifuDataGridViewDeparment.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(184)))), ((int)(((byte)(196)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Crimson;
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(16)))), ((int)(((byte)(48)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.CurrentTheme.Name = null;
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(208)))), ((int)(((byte)(216)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            this.bunifuDataGridViewDeparment.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(208)))), ((int)(((byte)(216)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(114)))), ((int)(((byte)(138)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewDeparment.DefaultCellStyle = dataGridViewCellStyle6;
            this.bunifuDataGridViewDeparment.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewDeparment.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(184)))), ((int)(((byte)(196)))));
            this.bunifuDataGridViewDeparment.HeaderBackColor = System.Drawing.Color.Crimson;
            this.bunifuDataGridViewDeparment.HeaderBackColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewDeparment.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewDeparment.Location = new System.Drawing.Point(37, 107);
            this.bunifuDataGridViewDeparment.Name = "bunifuDataGridViewDeparment";
            this.bunifuDataGridViewDeparment.RowHeadersVisible = false;
            this.bunifuDataGridViewDeparment.RowTemplate.Height = 40;
            this.bunifuDataGridViewDeparment.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewDeparment.Size = new System.Drawing.Size(433, 550);
            this.bunifuDataGridViewDeparment.TabIndex = 4;
            this.bunifuDataGridViewDeparment.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Crimson;
            this.bunifuDataGridViewDeparment.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridViewDeparment_CellDoubleClick);
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 100;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // FormMainDeptMajor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Name = "FormMainDeptMajor";
            this.Size = new System.Drawing.Size(989, 792);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewMajor)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewDeparment)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewDeparment;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewMajor;
        private System.Windows.Forms.PictureBox pictureBox7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMajorDelete;
        private System.Windows.Forms.PictureBox pictureBox8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMajorEdit;
        private System.Windows.Forms.PictureBox pictureBox9;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonMajorAdd;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonDepartmentAdd;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonDepartmentDelete;
        private System.Windows.Forms.PictureBox pictureBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonDepartmentEdit;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
    }
}
