namespace DO_AN_CUA_HAN.View
{
    partial class FormTestDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormTestDetail));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel3 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.comboBoxTestType = new Bunifu.UI.WinForms.BunifuDropdown();
            this.buttonInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.labelState = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.listSelectedTestType = new System.Windows.Forms.ListBox();
            this.buttonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonOk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonRemove = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.labelX5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxResult = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelX3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.comboBoxState = new Bunifu.UI.WinForms.BunifuDropdown();
            this.dateCreate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.labelBirthday = new Bunifu.UI.WinForms.BunifuLabel();
            this.labelX4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.labelX2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxPatientID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelX1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxStaffID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBoxTCID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelRoleID = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel24 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel3.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 50;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel3);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(157)))), ((int)(((byte)(191)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(109)))), ((int)(((byte)(160)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(595, 707);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // bunifuShadowPanel3
            // 
            this.bunifuShadowPanel3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel3.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel3.BorderRadius = 20;
            this.bunifuShadowPanel3.BorderThickness = 2;
            this.bunifuShadowPanel3.Controls.Add(this.comboBoxTestType);
            this.bunifuShadowPanel3.Controls.Add(this.buttonInsert);
            this.bunifuShadowPanel3.Controls.Add(this.labelState);
            this.bunifuShadowPanel3.Controls.Add(this.bunifuLabel11);
            this.bunifuShadowPanel3.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel3.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel3.Location = new System.Drawing.Point(34, 316);
            this.bunifuShadowPanel3.Name = "bunifuShadowPanel3";
            this.bunifuShadowPanel3.PanelColor = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel3.PanelColor2 = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel3.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel3.ShadowDept = 2;
            this.bunifuShadowPanel3.ShadowDepth = 5;
            this.bunifuShadowPanel3.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel3.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel3.Size = new System.Drawing.Size(519, 132);
            this.bunifuShadowPanel3.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel3.TabIndex = 42;
            // 
            // comboBoxTestType
            // 
            this.comboBoxTestType.BackColor = System.Drawing.Color.Transparent;
            this.comboBoxTestType.BackgroundColor = System.Drawing.Color.White;
            this.comboBoxTestType.BorderColor = System.Drawing.Color.Silver;
            this.comboBoxTestType.BorderRadius = 1;
            this.comboBoxTestType.Color = System.Drawing.Color.Silver;
            this.comboBoxTestType.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.comboBoxTestType.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.comboBoxTestType.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.comboBoxTestType.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.comboBoxTestType.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.comboBoxTestType.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.comboBoxTestType.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.comboBoxTestType.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.comboBoxTestType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxTestType.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.comboBoxTestType.FillDropDown = true;
            this.comboBoxTestType.FillIndicator = false;
            this.comboBoxTestType.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.comboBoxTestType.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.comboBoxTestType.ForeColor = System.Drawing.Color.Black;
            this.comboBoxTestType.FormattingEnabled = true;
            this.comboBoxTestType.Icon = null;
            this.comboBoxTestType.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.comboBoxTestType.IndicatorColor = System.Drawing.Color.Gray;
            this.comboBoxTestType.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.comboBoxTestType.ItemBackColor = System.Drawing.Color.White;
            this.comboBoxTestType.ItemBorderColor = System.Drawing.Color.White;
            this.comboBoxTestType.ItemForeColor = System.Drawing.Color.Black;
            this.comboBoxTestType.ItemHeight = 26;
            this.comboBoxTestType.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.comboBoxTestType.ItemHighLightForeColor = System.Drawing.Color.White;
            this.comboBoxTestType.ItemTopMargin = 3;
            this.comboBoxTestType.Location = new System.Drawing.Point(184, 50);
            this.comboBoxTestType.Margin = new System.Windows.Forms.Padding(2);
            this.comboBoxTestType.Name = "comboBoxTestType";
            this.comboBoxTestType.Size = new System.Drawing.Size(311, 32);
            this.comboBoxTestType.TabIndex = 24;
            this.comboBoxTestType.Text = null;
            this.comboBoxTestType.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.comboBoxTestType.TextLeftMargin = 5;
            // 
            // buttonInsert
            // 
            this.buttonInsert.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonInsert.AllowAnimations = true;
            this.buttonInsert.AllowMouseEffects = true;
            this.buttonInsert.AllowToggling = false;
            this.buttonInsert.AnimationSpeed = 200;
            this.buttonInsert.AutoGenerateColors = false;
            this.buttonInsert.AutoRoundBorders = false;
            this.buttonInsert.AutoSizeLeftIcon = true;
            this.buttonInsert.AutoSizeRightIcon = true;
            this.buttonInsert.BackColor = System.Drawing.Color.Transparent;
            this.buttonInsert.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonInsert.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonInsert.BackgroundImage")));
            this.buttonInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.ButtonText = "Thêm";
            this.buttonInsert.ButtonTextMarginLeft = 0;
            this.buttonInsert.ColorContrastOnClick = 45;
            this.buttonInsert.ColorContrastOnHover = 45;
            this.buttonInsert.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonInsert.CustomizableEdges = borderEdges1;
            this.buttonInsert.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonInsert.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonInsert.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonInsert.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonInsert.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonInsert.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonInsert.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonInsert.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonInsert.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonInsert.IconMarginLeft = 11;
            this.buttonInsert.IconPadding = 10;
            this.buttonInsert.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonInsert.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonInsert.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonInsert.IconSize = 25;
            this.buttonInsert.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonInsert.IdleBorderRadius = 15;
            this.buttonInsert.IdleBorderThickness = 1;
            this.buttonInsert.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonInsert.IdleIconLeftImage = null;
            this.buttonInsert.IdleIconRightImage = null;
            this.buttonInsert.IndicateFocus = false;
            this.buttonInsert.Location = new System.Drawing.Point(253, 89);
            this.buttonInsert.Name = "buttonInsert";
            this.buttonInsert.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonInsert.OnDisabledState.BorderRadius = 15;
            this.buttonInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.OnDisabledState.BorderThickness = 1;
            this.buttonInsert.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonInsert.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonInsert.OnDisabledState.IconLeftImage = null;
            this.buttonInsert.OnDisabledState.IconRightImage = null;
            this.buttonInsert.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonInsert.onHoverState.BorderRadius = 15;
            this.buttonInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.onHoverState.BorderThickness = 1;
            this.buttonInsert.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonInsert.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonInsert.onHoverState.IconLeftImage = null;
            this.buttonInsert.onHoverState.IconRightImage = null;
            this.buttonInsert.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonInsert.OnIdleState.BorderRadius = 15;
            this.buttonInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.OnIdleState.BorderThickness = 1;
            this.buttonInsert.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonInsert.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonInsert.OnIdleState.IconLeftImage = null;
            this.buttonInsert.OnIdleState.IconRightImage = null;
            this.buttonInsert.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonInsert.OnPressedState.BorderRadius = 15;
            this.buttonInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonInsert.OnPressedState.BorderThickness = 1;
            this.buttonInsert.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonInsert.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonInsert.OnPressedState.IconLeftImage = null;
            this.buttonInsert.OnPressedState.IconRightImage = null;
            this.buttonInsert.Size = new System.Drawing.Size(76, 30);
            this.buttonInsert.TabIndex = 23;
            this.buttonInsert.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonInsert.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonInsert.TextMarginLeft = 0;
            this.buttonInsert.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonInsert.UseDefaultRadiusAndThickness = true;
            this.buttonInsert.Click += new System.EventHandler(this.buttonInsert_Click);
            // 
            // labelState
            // 
            this.labelState.AllowParentOverrides = false;
            this.labelState.AutoEllipsis = false;
            this.labelState.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelState.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelState.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelState.Location = new System.Drawing.Point(28, 52);
            this.labelState.Name = "labelState";
            this.labelState.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelState.Size = new System.Drawing.Size(95, 17);
            this.labelState.TabIndex = 2;
            this.labelState.Text = "Tên xét nghiệm";
            this.labelState.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelState.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel11.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel11.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel11.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel11.Location = new System.Drawing.Point(196, 21);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(135, 19);
            this.bunifuLabel11.TabIndex = 1;
            this.bunifuLabel11.Text = "LOẠI XÉT NGHIỆM";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel1.BorderRadius = 20;
            this.bunifuShadowPanel1.BorderThickness = 2;
            this.bunifuShadowPanel1.Controls.Add(this.listSelectedTestType);
            this.bunifuShadowPanel1.Controls.Add(this.buttonClose);
            this.bunifuShadowPanel1.Controls.Add(this.buttonOk);
            this.bunifuShadowPanel1.Controls.Add(this.buttonRemove);
            this.bunifuShadowPanel1.Controls.Add(this.labelX5);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxResult);
            this.bunifuShadowPanel1.Controls.Add(this.labelX3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(34, 465);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(519, 220);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // listSelectedTestType
            // 
            this.listSelectedTestType.AccessibleRole = System.Windows.Forms.AccessibleRole.Clock;
            this.listSelectedTestType.ForeColor = System.Drawing.Color.Black;
            this.listSelectedTestType.FormattingEnabled = true;
            this.listSelectedTestType.Location = new System.Drawing.Point(184, 55);
            this.listSelectedTestType.Margin = new System.Windows.Forms.Padding(2);
            this.listSelectedTestType.Name = "listSelectedTestType";
            this.listSelectedTestType.Size = new System.Drawing.Size(311, 43);
            this.listSelectedTestType.TabIndex = 27;
            // 
            // buttonClose
            // 
            this.buttonClose.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonClose.AllowAnimations = true;
            this.buttonClose.AllowMouseEffects = true;
            this.buttonClose.AllowToggling = false;
            this.buttonClose.AnimationSpeed = 200;
            this.buttonClose.AutoGenerateColors = false;
            this.buttonClose.AutoRoundBorders = false;
            this.buttonClose.AutoSizeLeftIcon = true;
            this.buttonClose.AutoSizeRightIcon = true;
            this.buttonClose.BackColor = System.Drawing.Color.Transparent;
            this.buttonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonClose.BackgroundImage")));
            this.buttonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.ButtonText = "Đóng";
            this.buttonClose.ButtonTextMarginLeft = 0;
            this.buttonClose.ColorContrastOnClick = 45;
            this.buttonClose.ColorContrastOnHover = 45;
            this.buttonClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonClose.CustomizableEdges = borderEdges2;
            this.buttonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonClose.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonClose.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonClose.IconMarginLeft = 11;
            this.buttonClose.IconPadding = 10;
            this.buttonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonClose.IconSize = 25;
            this.buttonClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleBorderRadius = 15;
            this.buttonClose.IdleBorderThickness = 1;
            this.buttonClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleIconLeftImage = null;
            this.buttonClose.IdleIconRightImage = null;
            this.buttonClose.IndicateFocus = false;
            this.buttonClose.Location = new System.Drawing.Point(409, 173);
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.OnDisabledState.BorderRadius = 15;
            this.buttonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnDisabledState.BorderThickness = 1;
            this.buttonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.OnDisabledState.IconLeftImage = null;
            this.buttonClose.OnDisabledState.IconRightImage = null;
            this.buttonClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonClose.onHoverState.BorderRadius = 15;
            this.buttonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.onHoverState.BorderThickness = 1;
            this.buttonClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonClose.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonClose.onHoverState.IconLeftImage = null;
            this.buttonClose.onHoverState.IconRightImage = null;
            this.buttonClose.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.BorderRadius = 15;
            this.buttonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnIdleState.BorderThickness = 1;
            this.buttonClose.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonClose.OnIdleState.IconLeftImage = null;
            this.buttonClose.OnIdleState.IconRightImage = null;
            this.buttonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.BorderRadius = 15;
            this.buttonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnPressedState.BorderThickness = 1;
            this.buttonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonClose.OnPressedState.IconLeftImage = null;
            this.buttonClose.OnPressedState.IconRightImage = null;
            this.buttonClose.Size = new System.Drawing.Size(76, 30);
            this.buttonClose.TabIndex = 26;
            this.buttonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonClose.TextMarginLeft = 0;
            this.buttonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonClose.UseDefaultRadiusAndThickness = true;
            this.buttonClose.Click += new System.EventHandler(this.buttonClose_Click);
            // 
            // buttonOk
            // 
            this.buttonOk.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonOk.AllowAnimations = true;
            this.buttonOk.AllowMouseEffects = true;
            this.buttonOk.AllowToggling = false;
            this.buttonOk.AnimationSpeed = 200;
            this.buttonOk.AutoGenerateColors = false;
            this.buttonOk.AutoRoundBorders = false;
            this.buttonOk.AutoSizeLeftIcon = true;
            this.buttonOk.AutoSizeRightIcon = true;
            this.buttonOk.BackColor = System.Drawing.Color.Transparent;
            this.buttonOk.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonOk.BackgroundImage")));
            this.buttonOk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.ButtonText = "Đồng ý";
            this.buttonOk.ButtonTextMarginLeft = 0;
            this.buttonOk.ColorContrastOnClick = 45;
            this.buttonOk.ColorContrastOnHover = 45;
            this.buttonOk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.buttonOk.CustomizableEdges = borderEdges3;
            this.buttonOk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonOk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonOk.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonOk.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonOk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonOk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonOk.IconMarginLeft = 11;
            this.buttonOk.IconPadding = 10;
            this.buttonOk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonOk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonOk.IconSize = 25;
            this.buttonOk.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleBorderRadius = 15;
            this.buttonOk.IdleBorderThickness = 1;
            this.buttonOk.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleIconLeftImage = null;
            this.buttonOk.IdleIconRightImage = null;
            this.buttonOk.IndicateFocus = false;
            this.buttonOk.Location = new System.Drawing.Point(315, 173);
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.OnDisabledState.BorderRadius = 15;
            this.buttonOk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnDisabledState.BorderThickness = 1;
            this.buttonOk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.OnDisabledState.IconLeftImage = null;
            this.buttonOk.OnDisabledState.IconRightImage = null;
            this.buttonOk.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonOk.onHoverState.BorderRadius = 15;
            this.buttonOk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.onHoverState.BorderThickness = 1;
            this.buttonOk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonOk.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonOk.onHoverState.IconLeftImage = null;
            this.buttonOk.onHoverState.IconRightImage = null;
            this.buttonOk.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.BorderRadius = 15;
            this.buttonOk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnIdleState.BorderThickness = 1;
            this.buttonOk.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonOk.OnIdleState.IconLeftImage = null;
            this.buttonOk.OnIdleState.IconRightImage = null;
            this.buttonOk.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.BorderRadius = 15;
            this.buttonOk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnPressedState.BorderThickness = 1;
            this.buttonOk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonOk.OnPressedState.IconLeftImage = null;
            this.buttonOk.OnPressedState.IconRightImage = null;
            this.buttonOk.Size = new System.Drawing.Size(76, 30);
            this.buttonOk.TabIndex = 25;
            this.buttonOk.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonOk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonOk.TextMarginLeft = 0;
            this.buttonOk.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonOk.UseDefaultRadiusAndThickness = true;
            this.buttonOk.Click += new System.EventHandler(this.buttonOk_Click);
            // 
            // buttonRemove
            // 
            this.buttonRemove.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonRemove.AllowAnimations = true;
            this.buttonRemove.AllowMouseEffects = true;
            this.buttonRemove.AllowToggling = false;
            this.buttonRemove.AnimationSpeed = 200;
            this.buttonRemove.AutoGenerateColors = false;
            this.buttonRemove.AutoRoundBorders = false;
            this.buttonRemove.AutoSizeLeftIcon = true;
            this.buttonRemove.AutoSizeRightIcon = true;
            this.buttonRemove.BackColor = System.Drawing.Color.Transparent;
            this.buttonRemove.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonRemove.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonRemove.BackgroundImage")));
            this.buttonRemove.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonRemove.ButtonText = "Bỏ ";
            this.buttonRemove.ButtonTextMarginLeft = 0;
            this.buttonRemove.ColorContrastOnClick = 45;
            this.buttonRemove.ColorContrastOnHover = 45;
            this.buttonRemove.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.buttonRemove.CustomizableEdges = borderEdges4;
            this.buttonRemove.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonRemove.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonRemove.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonRemove.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonRemove.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonRemove.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonRemove.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonRemove.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonRemove.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonRemove.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonRemove.IconMarginLeft = 11;
            this.buttonRemove.IconPadding = 10;
            this.buttonRemove.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonRemove.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonRemove.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonRemove.IconSize = 25;
            this.buttonRemove.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonRemove.IdleBorderRadius = 15;
            this.buttonRemove.IdleBorderThickness = 1;
            this.buttonRemove.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonRemove.IdleIconLeftImage = null;
            this.buttonRemove.IdleIconRightImage = null;
            this.buttonRemove.IndicateFocus = false;
            this.buttonRemove.Location = new System.Drawing.Point(222, 173);
            this.buttonRemove.Name = "buttonRemove";
            this.buttonRemove.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonRemove.OnDisabledState.BorderRadius = 15;
            this.buttonRemove.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonRemove.OnDisabledState.BorderThickness = 1;
            this.buttonRemove.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonRemove.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonRemove.OnDisabledState.IconLeftImage = null;
            this.buttonRemove.OnDisabledState.IconRightImage = null;
            this.buttonRemove.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonRemove.onHoverState.BorderRadius = 15;
            this.buttonRemove.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonRemove.onHoverState.BorderThickness = 1;
            this.buttonRemove.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonRemove.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonRemove.onHoverState.IconLeftImage = null;
            this.buttonRemove.onHoverState.IconRightImage = null;
            this.buttonRemove.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonRemove.OnIdleState.BorderRadius = 15;
            this.buttonRemove.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonRemove.OnIdleState.BorderThickness = 1;
            this.buttonRemove.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonRemove.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonRemove.OnIdleState.IconLeftImage = null;
            this.buttonRemove.OnIdleState.IconRightImage = null;
            this.buttonRemove.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonRemove.OnPressedState.BorderRadius = 15;
            this.buttonRemove.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonRemove.OnPressedState.BorderThickness = 1;
            this.buttonRemove.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonRemove.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonRemove.OnPressedState.IconLeftImage = null;
            this.buttonRemove.OnPressedState.IconRightImage = null;
            this.buttonRemove.Size = new System.Drawing.Size(76, 30);
            this.buttonRemove.TabIndex = 24;
            this.buttonRemove.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonRemove.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonRemove.TextMarginLeft = 0;
            this.buttonRemove.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonRemove.UseDefaultRadiusAndThickness = true;
            this.buttonRemove.Click += new System.EventHandler(this.buttonRemove_Click);
            // 
            // labelX5
            // 
            this.labelX5.AllowParentOverrides = false;
            this.labelX5.AutoEllipsis = false;
            this.labelX5.CursorType = null;
            this.labelX5.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelX5.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelX5.Location = new System.Drawing.Point(28, 128);
            this.labelX5.Name = "labelX5";
            this.labelX5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX5.Size = new System.Drawing.Size(47, 17);
            this.labelX5.TabIndex = 16;
            this.labelX5.Text = "Kết quả";
            this.labelX5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textBoxResult
            // 
            this.textBoxResult.AcceptsReturn = false;
            this.textBoxResult.AcceptsTab = false;
            this.textBoxResult.AnimationSpeed = 200;
            this.textBoxResult.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxResult.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxResult.BackColor = System.Drawing.Color.White;
            this.textBoxResult.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxResult.BackgroundImage")));
            this.textBoxResult.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxResult.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxResult.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxResult.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxResult.BorderRadius = 10;
            this.textBoxResult.BorderThickness = 1;
            this.textBoxResult.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxResult.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxResult.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxResult.DefaultText = "";
            this.textBoxResult.FillColor = System.Drawing.Color.White;
            this.textBoxResult.ForeColor = System.Drawing.Color.Black;
            this.textBoxResult.HideSelection = true;
            this.textBoxResult.IconLeft = null;
            this.textBoxResult.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxResult.IconPadding = 10;
            this.textBoxResult.IconRight = null;
            this.textBoxResult.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxResult.Lines = new string[0];
            this.textBoxResult.Location = new System.Drawing.Point(184, 109);
            this.textBoxResult.MaxLength = 32767;
            this.textBoxResult.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxResult.Modified = false;
            this.textBoxResult.Multiline = false;
            this.textBoxResult.Name = "textBoxResult";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxResult.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxResult.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxResult.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxResult.OnIdleState = stateProperties4;
            this.textBoxResult.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxResult.PasswordChar = '\0';
            this.textBoxResult.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxResult.PlaceholderText = "Nhập kết quả";
            this.textBoxResult.ReadOnly = false;
            this.textBoxResult.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxResult.SelectedText = "";
            this.textBoxResult.SelectionLength = 0;
            this.textBoxResult.SelectionStart = 0;
            this.textBoxResult.ShortcutsEnabled = true;
            this.textBoxResult.Size = new System.Drawing.Size(309, 46);
            this.textBoxResult.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxResult.TabIndex = 13;
            this.textBoxResult.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxResult.TextMarginBottom = 0;
            this.textBoxResult.TextMarginLeft = 3;
            this.textBoxResult.TextMarginTop = 0;
            this.textBoxResult.TextPlaceholder = "Nhập kết quả";
            this.textBoxResult.UseSystemPasswordChar = false;
            this.textBoxResult.WordWrap = true;
            // 
            // labelX3
            // 
            this.labelX3.AllowParentOverrides = false;
            this.labelX3.AutoEllipsis = false;
            this.labelX3.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelX3.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelX3.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelX3.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelX3.Location = new System.Drawing.Point(28, 67);
            this.labelX3.Name = "labelX3";
            this.labelX3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX3.Size = new System.Drawing.Size(135, 17);
            this.labelX3.TabIndex = 2;
            this.labelX3.Text = "Danh sách xét nghiệm";
            this.labelX3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(199, 24);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(158, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "CHI TIẾT TOA THUỐC";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel2.BorderRadius = 20;
            this.bunifuShadowPanel2.BorderThickness = 2;
            this.bunifuShadowPanel2.Controls.Add(this.comboBoxState);
            this.bunifuShadowPanel2.Controls.Add(this.dateCreate);
            this.bunifuShadowPanel2.Controls.Add(this.labelBirthday);
            this.bunifuShadowPanel2.Controls.Add(this.labelX4);
            this.bunifuShadowPanel2.Controls.Add(this.labelX2);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxPatientID);
            this.bunifuShadowPanel2.Controls.Add(this.labelX1);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxStaffID);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxTCID);
            this.bunifuShadowPanel2.Controls.Add(this.labelRoleID);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel24);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(34, 36);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(519, 257);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 41;
            // 
            // comboBoxState
            // 
            this.comboBoxState.BackColor = System.Drawing.Color.Transparent;
            this.comboBoxState.BackgroundColor = System.Drawing.Color.White;
            this.comboBoxState.BorderColor = System.Drawing.Color.Silver;
            this.comboBoxState.BorderRadius = 1;
            this.comboBoxState.Color = System.Drawing.Color.Silver;
            this.comboBoxState.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.comboBoxState.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.comboBoxState.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.comboBoxState.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.comboBoxState.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.comboBoxState.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.comboBoxState.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.comboBoxState.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.comboBoxState.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxState.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.comboBoxState.FillDropDown = true;
            this.comboBoxState.FillIndicator = false;
            this.comboBoxState.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.comboBoxState.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.comboBoxState.ForeColor = System.Drawing.Color.Black;
            this.comboBoxState.FormattingEnabled = true;
            this.comboBoxState.Icon = null;
            this.comboBoxState.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.comboBoxState.IndicatorColor = System.Drawing.Color.Gray;
            this.comboBoxState.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.comboBoxState.ItemBackColor = System.Drawing.Color.White;
            this.comboBoxState.ItemBorderColor = System.Drawing.Color.White;
            this.comboBoxState.ItemForeColor = System.Drawing.Color.Black;
            this.comboBoxState.ItemHeight = 26;
            this.comboBoxState.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.comboBoxState.ItemHighLightForeColor = System.Drawing.Color.White;
            this.comboBoxState.Items.AddRange(new object[] {
            "Chưa xét nghiệm",
            "Đã xét nghiệm"});
            this.comboBoxState.ItemTopMargin = 3;
            this.comboBoxState.Location = new System.Drawing.Point(184, 207);
            this.comboBoxState.Name = "comboBoxState";
            this.comboBoxState.Size = new System.Drawing.Size(213, 32);
            this.comboBoxState.TabIndex = 36;
            this.comboBoxState.Text = null;
            this.comboBoxState.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.comboBoxState.TextLeftMargin = 5;
            // 
            // dateCreate
            // 
            this.dateCreate.AllowDrop = true;
            this.dateCreate.BackColor = System.Drawing.Color.Transparent;
            this.dateCreate.BorderRadius = 5;
            this.dateCreate.Color = System.Drawing.Color.Gainsboro;
            this.dateCreate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dateCreate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateCreate.DisabledColor = System.Drawing.Color.Gray;
            this.dateCreate.DisplayWeekNumbers = false;
            this.dateCreate.DPHeight = 0;
            this.dateCreate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dateCreate.FillDatePicker = false;
            this.dateCreate.Font = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.dateCreate.ForeColor = System.Drawing.Color.Black;
            this.dateCreate.Icon = ((System.Drawing.Image)(resources.GetObject("dateCreate.Icon")));
            this.dateCreate.IconColor = System.Drawing.Color.DimGray;
            this.dateCreate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateCreate.LeftTextMargin = 5;
            this.dateCreate.Location = new System.Drawing.Point(184, 174);
            this.dateCreate.MinimumSize = new System.Drawing.Size(4, 32);
            this.dateCreate.Name = "dateCreate";
            this.dateCreate.Size = new System.Drawing.Size(209, 32);
            this.dateCreate.TabIndex = 23;
            this.dateCreate.Value = new System.DateTime(2023, 12, 8, 4, 30, 0, 0);
            // 
            // labelBirthday
            // 
            this.labelBirthday.AllowParentOverrides = false;
            this.labelBirthday.AutoEllipsis = false;
            this.labelBirthday.CursorType = null;
            this.labelBirthday.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelBirthday.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelBirthday.Location = new System.Drawing.Point(28, 176);
            this.labelBirthday.Name = "labelBirthday";
            this.labelBirthday.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelBirthday.Size = new System.Drawing.Size(54, 17);
            this.labelBirthday.TabIndex = 22;
            this.labelBirthday.Text = "Ngày lập";
            this.labelBirthday.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelBirthday.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // labelX4
            // 
            this.labelX4.AllowParentOverrides = false;
            this.labelX4.AutoEllipsis = false;
            this.labelX4.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelX4.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelX4.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelX4.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelX4.Location = new System.Drawing.Point(28, 211);
            this.labelX4.Name = "labelX4";
            this.labelX4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX4.Size = new System.Drawing.Size(64, 17);
            this.labelX4.TabIndex = 19;
            this.labelX4.Text = "Trạng thái";
            this.labelX4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // labelX2
            // 
            this.labelX2.AllowParentOverrides = false;
            this.labelX2.AutoEllipsis = false;
            this.labelX2.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelX2.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelX2.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelX2.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelX2.Location = new System.Drawing.Point(28, 140);
            this.labelX2.Name = "labelX2";
            this.labelX2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX2.Size = new System.Drawing.Size(87, 17);
            this.labelX2.TabIndex = 17;
            this.labelX2.Text = "Mã bệnh nhân";
            this.labelX2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textBoxPatientID
            // 
            this.textBoxPatientID.AcceptsReturn = false;
            this.textBoxPatientID.AcceptsTab = false;
            this.textBoxPatientID.AnimationSpeed = 200;
            this.textBoxPatientID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxPatientID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxPatientID.BackColor = System.Drawing.Color.White;
            this.textBoxPatientID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxPatientID.BackgroundImage")));
            this.textBoxPatientID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxPatientID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxPatientID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxPatientID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxPatientID.BorderRadius = 10;
            this.textBoxPatientID.BorderThickness = 1;
            this.textBoxPatientID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxPatientID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxPatientID.DefaultText = "";
            this.textBoxPatientID.FillColor = System.Drawing.Color.White;
            this.textBoxPatientID.ForeColor = System.Drawing.Color.Black;
            this.textBoxPatientID.HideSelection = true;
            this.textBoxPatientID.IconLeft = null;
            this.textBoxPatientID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientID.IconPadding = 10;
            this.textBoxPatientID.IconRight = null;
            this.textBoxPatientID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientID.Lines = new string[0];
            this.textBoxPatientID.Location = new System.Drawing.Point(184, 135);
            this.textBoxPatientID.MaxLength = 32767;
            this.textBoxPatientID.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxPatientID.Modified = false;
            this.textBoxPatientID.Multiline = false;
            this.textBoxPatientID.Name = "textBoxPatientID";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxPatientID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientID.OnIdleState = stateProperties8;
            this.textBoxPatientID.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxPatientID.PasswordChar = '\0';
            this.textBoxPatientID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxPatientID.PlaceholderText = "Nhập mã bệnh nhân";
            this.textBoxPatientID.ReadOnly = true;
            this.textBoxPatientID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxPatientID.SelectedText = "";
            this.textBoxPatientID.SelectionLength = 0;
            this.textBoxPatientID.SelectionStart = 0;
            this.textBoxPatientID.ShortcutsEnabled = true;
            this.textBoxPatientID.Size = new System.Drawing.Size(309, 27);
            this.textBoxPatientID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxPatientID.TabIndex = 16;
            this.textBoxPatientID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxPatientID.TextMarginBottom = 0;
            this.textBoxPatientID.TextMarginLeft = 3;
            this.textBoxPatientID.TextMarginTop = 0;
            this.textBoxPatientID.TextPlaceholder = "Nhập mã bệnh nhân";
            this.textBoxPatientID.UseSystemPasswordChar = false;
            this.textBoxPatientID.WordWrap = true;
            // 
            // labelX1
            // 
            this.labelX1.AllowParentOverrides = false;
            this.labelX1.AutoEllipsis = false;
            this.labelX1.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelX1.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelX1.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelX1.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelX1.Location = new System.Drawing.Point(28, 98);
            this.labelX1.Name = "labelX1";
            this.labelX1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX1.Size = new System.Drawing.Size(83, 17);
            this.labelX1.TabIndex = 15;
            this.labelX1.Text = "Mã nhân viên";
            this.labelX1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textBoxStaffID
            // 
            this.textBoxStaffID.AcceptsReturn = false;
            this.textBoxStaffID.AcceptsTab = false;
            this.textBoxStaffID.AnimationSpeed = 200;
            this.textBoxStaffID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxStaffID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxStaffID.BackColor = System.Drawing.Color.White;
            this.textBoxStaffID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxStaffID.BackgroundImage")));
            this.textBoxStaffID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxStaffID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxStaffID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxStaffID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxStaffID.BorderRadius = 10;
            this.textBoxStaffID.BorderThickness = 1;
            this.textBoxStaffID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxStaffID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxStaffID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxStaffID.DefaultText = "";
            this.textBoxStaffID.FillColor = System.Drawing.Color.White;
            this.textBoxStaffID.ForeColor = System.Drawing.Color.Black;
            this.textBoxStaffID.HideSelection = true;
            this.textBoxStaffID.IconLeft = null;
            this.textBoxStaffID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxStaffID.IconPadding = 10;
            this.textBoxStaffID.IconRight = null;
            this.textBoxStaffID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxStaffID.Lines = new string[0];
            this.textBoxStaffID.Location = new System.Drawing.Point(184, 92);
            this.textBoxStaffID.MaxLength = 32767;
            this.textBoxStaffID.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxStaffID.Modified = false;
            this.textBoxStaffID.Multiline = false;
            this.textBoxStaffID.Name = "textBoxStaffID";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxStaffID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxStaffID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxStaffID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxStaffID.OnIdleState = stateProperties12;
            this.textBoxStaffID.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxStaffID.PasswordChar = '\0';
            this.textBoxStaffID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxStaffID.PlaceholderText = "Nhập mã nhân viên";
            this.textBoxStaffID.ReadOnly = true;
            this.textBoxStaffID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxStaffID.SelectedText = "";
            this.textBoxStaffID.SelectionLength = 0;
            this.textBoxStaffID.SelectionStart = 0;
            this.textBoxStaffID.ShortcutsEnabled = true;
            this.textBoxStaffID.Size = new System.Drawing.Size(309, 27);
            this.textBoxStaffID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxStaffID.TabIndex = 14;
            this.textBoxStaffID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxStaffID.TextMarginBottom = 0;
            this.textBoxStaffID.TextMarginLeft = 3;
            this.textBoxStaffID.TextMarginTop = 0;
            this.textBoxStaffID.TextPlaceholder = "Nhập mã nhân viên";
            this.textBoxStaffID.UseSystemPasswordChar = false;
            this.textBoxStaffID.WordWrap = true;
            // 
            // textBoxTCID
            // 
            this.textBoxTCID.AcceptsReturn = false;
            this.textBoxTCID.AcceptsTab = false;
            this.textBoxTCID.AnimationSpeed = 200;
            this.textBoxTCID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxTCID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxTCID.BackColor = System.Drawing.Color.White;
            this.textBoxTCID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxTCID.BackgroundImage")));
            this.textBoxTCID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxTCID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxTCID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxTCID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxTCID.BorderRadius = 20;
            this.textBoxTCID.BorderThickness = 1;
            this.textBoxTCID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxTCID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxTCID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxTCID.DefaultText = "";
            this.textBoxTCID.FillColor = System.Drawing.Color.White;
            this.textBoxTCID.ForeColor = System.Drawing.Color.Black;
            this.textBoxTCID.HideSelection = true;
            this.textBoxTCID.IconLeft = null;
            this.textBoxTCID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxTCID.IconPadding = 10;
            this.textBoxTCID.IconRight = null;
            this.textBoxTCID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxTCID.Lines = new string[0];
            this.textBoxTCID.Location = new System.Drawing.Point(184, 50);
            this.textBoxTCID.MaxLength = 32767;
            this.textBoxTCID.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxTCID.Modified = false;
            this.textBoxTCID.Multiline = false;
            this.textBoxTCID.Name = "textBoxTCID";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxTCID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxTCID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxTCID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxTCID.OnIdleState = stateProperties16;
            this.textBoxTCID.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxTCID.PasswordChar = '\0';
            this.textBoxTCID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxTCID.PlaceholderText = "Nhập mã phiếu xét nghiệm";
            this.textBoxTCID.ReadOnly = true;
            this.textBoxTCID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxTCID.SelectedText = "";
            this.textBoxTCID.SelectionLength = 0;
            this.textBoxTCID.SelectionStart = 0;
            this.textBoxTCID.ShortcutsEnabled = true;
            this.textBoxTCID.Size = new System.Drawing.Size(309, 27);
            this.textBoxTCID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxTCID.TabIndex = 12;
            this.textBoxTCID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxTCID.TextMarginBottom = 0;
            this.textBoxTCID.TextMarginLeft = 3;
            this.textBoxTCID.TextMarginTop = 0;
            this.textBoxTCID.TextPlaceholder = "Nhập mã phiếu xét nghiệm";
            this.textBoxTCID.UseSystemPasswordChar = false;
            this.textBoxTCID.WordWrap = true;
            // 
            // labelRoleID
            // 
            this.labelRoleID.AllowParentOverrides = false;
            this.labelRoleID.AutoEllipsis = false;
            this.labelRoleID.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelRoleID.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelRoleID.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelRoleID.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelRoleID.Location = new System.Drawing.Point(28, 57);
            this.labelRoleID.Name = "labelRoleID";
            this.labelRoleID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelRoleID.Size = new System.Drawing.Size(128, 17);
            this.labelRoleID.TabIndex = 2;
            this.labelRoleID.Text = "Mã phiếu xét nghiệm";
            this.labelRoleID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelRoleID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel24
            // 
            this.bunifuLabel24.AllowParentOverrides = false;
            this.bunifuLabel24.AutoEllipsis = false;
            this.bunifuLabel24.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel24.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel24.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel24.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel24.Location = new System.Drawing.Point(196, 20);
            this.bunifuLabel24.Name = "bunifuLabel24";
            this.bunifuLabel24.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel24.Size = new System.Drawing.Size(147, 19);
            this.bunifuLabel24.TabIndex = 1;
            this.bunifuLabel24.Text = "PHIẾU XÉT NGHIỆM";
            this.bunifuLabel24.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel24.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // FormTestDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(595, 707);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "FormTestDetail";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormPrescriptionDetail";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel3.ResumeLayout(false);
            this.bunifuShadowPanel3.PerformLayout();
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxTCID;
        private Bunifu.UI.WinForms.BunifuLabel labelRoleID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel24;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuLabel labelX5;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxResult;
        private Bunifu.UI.WinForms.BunifuLabel labelX3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxStaffID;
        private Bunifu.UI.WinForms.BunifuDatePicker dateCreate;
        private Bunifu.UI.WinForms.BunifuLabel labelBirthday;
        private Bunifu.UI.WinForms.BunifuLabel labelX4;
        private Bunifu.UI.WinForms.BunifuLabel labelX2;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxPatientID;
        private Bunifu.UI.WinForms.BunifuLabel labelX1;
        private Bunifu.UI.WinForms.BunifuDropdown comboBoxState;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel3;
        private Bunifu.UI.WinForms.BunifuLabel labelState;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonInsert;
        private Bunifu.UI.WinForms.BunifuDropdown comboBoxTestType;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonOk;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonRemove;
        private System.Windows.Forms.ListBox listSelectedTestType;
    }
}