namespace DO_AN_CUA_HAN.View
{
    partial class FormMaterialDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMaterialDetail));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.labelQuantity = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonOk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.labelPrice = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelMaterialName = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxMaterialName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBoxMaterialID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelMaterialID = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel24 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 50;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel2);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(157)))), ((int)(((byte)(191)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(109)))), ((int)(((byte)(160)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(616, 481);
            this.bunifuGradientPanel1.TabIndex = 2;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel2.BorderRadius = 20;
            this.bunifuShadowPanel2.BorderThickness = 2;
            this.bunifuShadowPanel2.Controls.Add(this.labelQuantity);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxQuantity);
            this.bunifuShadowPanel2.Controls.Add(this.buttonClose);
            this.bunifuShadowPanel2.Controls.Add(this.buttonOk);
            this.bunifuShadowPanel2.Controls.Add(this.labelPrice);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxPrice);
            this.bunifuShadowPanel2.Controls.Add(this.labelMaterialName);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxMaterialName);
            this.bunifuShadowPanel2.Controls.Add(this.textBoxMaterialID);
            this.bunifuShadowPanel2.Controls.Add(this.labelMaterialID);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuLabel24);
            this.bunifuShadowPanel2.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(42, 47);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(521, 384);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 41;
            this.bunifuToolTip1.SetToolTip(this.bunifuShadowPanel2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuShadowPanel2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuShadowPanel2, "");
            // 
            // labelQuantity
            // 
            this.labelQuantity.AllowParentOverrides = false;
            this.labelQuantity.AutoEllipsis = false;
            this.labelQuantity.CursorType = null;
            this.labelQuantity.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelQuantity.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelQuantity.Location = new System.Drawing.Point(41, 226);
            this.labelQuantity.Name = "labelQuantity";
            this.labelQuantity.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelQuantity.Size = new System.Drawing.Size(55, 17);
            this.labelQuantity.TabIndex = 33;
            this.labelQuantity.Text = "Số lượng";
            this.labelQuantity.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelQuantity.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelQuantity, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelQuantity, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelQuantity, "");
            // 
            // textBoxQuantity
            // 
            this.textBoxQuantity.AcceptsReturn = false;
            this.textBoxQuantity.AcceptsTab = false;
            this.textBoxQuantity.AnimationSpeed = 200;
            this.textBoxQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxQuantity.BackColor = System.Drawing.Color.White;
            this.textBoxQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxQuantity.BackgroundImage")));
            this.textBoxQuantity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxQuantity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxQuantity.BorderRadius = 10;
            this.textBoxQuantity.BorderThickness = 1;
            this.textBoxQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxQuantity.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxQuantity.DefaultText = "";
            this.textBoxQuantity.FillColor = System.Drawing.Color.White;
            this.textBoxQuantity.ForeColor = System.Drawing.Color.Black;
            this.textBoxQuantity.HideSelection = true;
            this.textBoxQuantity.IconLeft = null;
            this.textBoxQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxQuantity.IconPadding = 10;
            this.textBoxQuantity.IconRight = null;
            this.textBoxQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxQuantity.Lines = new string[0];
            this.textBoxQuantity.Location = new System.Drawing.Point(155, 212);
            this.textBoxQuantity.MaxLength = 32767;
            this.textBoxQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxQuantity.Modified = false;
            this.textBoxQuantity.Multiline = false;
            this.textBoxQuantity.Name = "textBoxQuantity";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxQuantity.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxQuantity.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxQuantity.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxQuantity.OnIdleState = stateProperties4;
            this.textBoxQuantity.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.textBoxQuantity.PasswordChar = '\0';
            this.textBoxQuantity.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxQuantity.PlaceholderText = "Nhập số lượng vật tư";
            this.textBoxQuantity.ReadOnly = false;
            this.textBoxQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxQuantity.SelectedText = "";
            this.textBoxQuantity.SelectionLength = 0;
            this.textBoxQuantity.SelectionStart = 0;
            this.textBoxQuantity.ShortcutsEnabled = true;
            this.textBoxQuantity.Size = new System.Drawing.Size(291, 40);
            this.textBoxQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxQuantity.TabIndex = 32;
            this.textBoxQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxQuantity.TextMarginBottom = 0;
            this.textBoxQuantity.TextMarginLeft = 3;
            this.textBoxQuantity.TextMarginTop = 0;
            this.textBoxQuantity.TextPlaceholder = "Nhập số lượng vật tư";
            this.bunifuToolTip1.SetToolTip(this.textBoxQuantity, "Chỉ cho phép nhập số");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxQuantity, null);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxQuantity, "Warning");
            this.textBoxQuantity.UseSystemPasswordChar = false;
            this.textBoxQuantity.WordWrap = true;
            this.textBoxQuantity.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.textBoxQuantity_KeyPress);
            // 
            // buttonClose
            // 
            this.buttonClose.AllowAnimations = true;
            this.buttonClose.AllowMouseEffects = true;
            this.buttonClose.AllowToggling = false;
            this.buttonClose.AnimationSpeed = 200;
            this.buttonClose.AutoGenerateColors = false;
            this.buttonClose.AutoRoundBorders = false;
            this.buttonClose.AutoSizeLeftIcon = true;
            this.buttonClose.AutoSizeRightIcon = true;
            this.buttonClose.BackColor = System.Drawing.Color.Transparent;
            this.buttonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonClose.BackgroundImage")));
            this.buttonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.ButtonText = "Thoát";
            this.buttonClose.ButtonTextMarginLeft = 0;
            this.buttonClose.ColorContrastOnClick = 45;
            this.buttonClose.ColorContrastOnHover = 45;
            this.buttonClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonClose.CustomizableEdges = borderEdges1;
            this.buttonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonClose.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonClose.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonClose.IconMarginLeft = 11;
            this.buttonClose.IconPadding = 10;
            this.buttonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonClose.IconSize = 25;
            this.buttonClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleBorderRadius = 15;
            this.buttonClose.IdleBorderThickness = 1;
            this.buttonClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleIconLeftImage = null;
            this.buttonClose.IdleIconRightImage = null;
            this.buttonClose.IndicateFocus = false;
            this.buttonClose.Location = new System.Drawing.Point(422, 329);
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.OnDisabledState.BorderRadius = 15;
            this.buttonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnDisabledState.BorderThickness = 1;
            this.buttonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.OnDisabledState.IconLeftImage = null;
            this.buttonClose.OnDisabledState.IconRightImage = null;
            this.buttonClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonClose.onHoverState.BorderRadius = 15;
            this.buttonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.onHoverState.BorderThickness = 1;
            this.buttonClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonClose.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonClose.onHoverState.IconLeftImage = null;
            this.buttonClose.onHoverState.IconRightImage = null;
            this.buttonClose.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.BorderRadius = 15;
            this.buttonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnIdleState.BorderThickness = 1;
            this.buttonClose.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonClose.OnIdleState.IconLeftImage = null;
            this.buttonClose.OnIdleState.IconRightImage = null;
            this.buttonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.BorderRadius = 15;
            this.buttonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnPressedState.BorderThickness = 1;
            this.buttonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonClose.OnPressedState.IconLeftImage = null;
            this.buttonClose.OnPressedState.IconRightImage = null;
            this.buttonClose.Size = new System.Drawing.Size(63, 37);
            this.buttonClose.TabIndex = 31;
            this.buttonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonClose.TextMarginLeft = 0;
            this.buttonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.buttonClose, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonClose, null);
            this.bunifuToolTip1.SetToolTipTitle(this.buttonClose, "");
            this.buttonClose.UseDefaultRadiusAndThickness = true;
            this.buttonClose.Click += new System.EventHandler(this.buttonClose_Click);
            // 
            // buttonOk
            // 
            this.buttonOk.AllowAnimations = true;
            this.buttonOk.AllowMouseEffects = true;
            this.buttonOk.AllowToggling = false;
            this.buttonOk.AnimationSpeed = 200;
            this.buttonOk.AutoGenerateColors = false;
            this.buttonOk.AutoRoundBorders = false;
            this.buttonOk.AutoSizeLeftIcon = true;
            this.buttonOk.AutoSizeRightIcon = true;
            this.buttonOk.BackColor = System.Drawing.Color.Transparent;
            this.buttonOk.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonOk.BackgroundImage")));
            this.buttonOk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.ButtonText = "Đồng ý";
            this.buttonOk.ButtonTextMarginLeft = 0;
            this.buttonOk.ColorContrastOnClick = 45;
            this.buttonOk.ColorContrastOnHover = 45;
            this.buttonOk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonOk.CustomizableEdges = borderEdges2;
            this.buttonOk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonOk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonOk.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonOk.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonOk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonOk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonOk.IconMarginLeft = 11;
            this.buttonOk.IconPadding = 10;
            this.buttonOk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonOk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonOk.IconSize = 25;
            this.buttonOk.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleBorderRadius = 15;
            this.buttonOk.IdleBorderThickness = 1;
            this.buttonOk.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleIconLeftImage = null;
            this.buttonOk.IdleIconRightImage = null;
            this.buttonOk.IndicateFocus = false;
            this.buttonOk.Location = new System.Drawing.Point(330, 329);
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.OnDisabledState.BorderRadius = 15;
            this.buttonOk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnDisabledState.BorderThickness = 1;
            this.buttonOk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.OnDisabledState.IconLeftImage = null;
            this.buttonOk.OnDisabledState.IconRightImage = null;
            this.buttonOk.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonOk.onHoverState.BorderRadius = 15;
            this.buttonOk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.onHoverState.BorderThickness = 1;
            this.buttonOk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonOk.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonOk.onHoverState.IconLeftImage = null;
            this.buttonOk.onHoverState.IconRightImage = null;
            this.buttonOk.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.BorderRadius = 15;
            this.buttonOk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnIdleState.BorderThickness = 1;
            this.buttonOk.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.buttonOk.OnIdleState.IconLeftImage = null;
            this.buttonOk.OnIdleState.IconRightImage = null;
            this.buttonOk.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.BorderRadius = 15;
            this.buttonOk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnPressedState.BorderThickness = 1;
            this.buttonOk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonOk.OnPressedState.IconLeftImage = null;
            this.buttonOk.OnPressedState.IconRightImage = null;
            this.buttonOk.Size = new System.Drawing.Size(63, 37);
            this.buttonOk.TabIndex = 30;
            this.buttonOk.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonOk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonOk.TextMarginLeft = 0;
            this.buttonOk.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.buttonOk, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonOk, null);
            this.bunifuToolTip1.SetToolTipTitle(this.buttonOk, "");
            this.buttonOk.UseDefaultRadiusAndThickness = true;
            this.buttonOk.Click += new System.EventHandler(this.buttonOk_Click);
            // 
            // labelPrice
            // 
            this.labelPrice.AllowParentOverrides = false;
            this.labelPrice.AutoEllipsis = false;
            this.labelPrice.CursorType = null;
            this.labelPrice.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelPrice.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelPrice.Location = new System.Drawing.Point(41, 290);
            this.labelPrice.Name = "labelPrice";
            this.labelPrice.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelPrice.Size = new System.Drawing.Size(48, 17);
            this.labelPrice.TabIndex = 27;
            this.labelPrice.Text = "Đơn giá";
            this.labelPrice.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelPrice.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelPrice, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelPrice, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelPrice, "");
            // 
            // textBoxPrice
            // 
            this.textBoxPrice.AcceptsReturn = false;
            this.textBoxPrice.AcceptsTab = false;
            this.textBoxPrice.AnimationSpeed = 200;
            this.textBoxPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxPrice.BackColor = System.Drawing.Color.White;
            this.textBoxPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxPrice.BackgroundImage")));
            this.textBoxPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxPrice.BorderRadius = 10;
            this.textBoxPrice.BorderThickness = 1;
            this.textBoxPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPrice.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxPrice.DefaultText = "";
            this.textBoxPrice.FillColor = System.Drawing.Color.White;
            this.textBoxPrice.ForeColor = System.Drawing.Color.Black;
            this.textBoxPrice.HideSelection = true;
            this.textBoxPrice.IconLeft = null;
            this.textBoxPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPrice.IconPadding = 10;
            this.textBoxPrice.IconRight = null;
            this.textBoxPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPrice.Lines = new string[0];
            this.textBoxPrice.Location = new System.Drawing.Point(155, 275);
            this.textBoxPrice.MaxLength = 32767;
            this.textBoxPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxPrice.Modified = false;
            this.textBoxPrice.Multiline = false;
            this.textBoxPrice.Name = "textBoxPrice";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPrice.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxPrice.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPrice.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPrice.OnIdleState = stateProperties8;
            this.textBoxPrice.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.textBoxPrice.PasswordChar = '\0';
            this.textBoxPrice.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxPrice.PlaceholderText = "Nhập đơn giá";
            this.textBoxPrice.ReadOnly = false;
            this.textBoxPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxPrice.SelectedText = "";
            this.textBoxPrice.SelectionLength = 0;
            this.textBoxPrice.SelectionStart = 0;
            this.textBoxPrice.ShortcutsEnabled = true;
            this.textBoxPrice.Size = new System.Drawing.Size(291, 40);
            this.textBoxPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxPrice.TabIndex = 26;
            this.textBoxPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxPrice.TextMarginBottom = 0;
            this.textBoxPrice.TextMarginLeft = 3;
            this.textBoxPrice.TextMarginTop = 0;
            this.textBoxPrice.TextPlaceholder = "Nhập đơn giá";
            this.bunifuToolTip1.SetToolTip(this.textBoxPrice, "Chỉ cho phép nhập số");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxPrice, global::DO_AN_CUA_HAN.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxPrice, "Warning");
            this.textBoxPrice.UseSystemPasswordChar = false;
            this.textBoxPrice.WordWrap = true;
            this.textBoxPrice.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.textBoxPrice_KeyPress);
            // 
            // labelMaterialName
            // 
            this.labelMaterialName.AllowParentOverrides = false;
            this.labelMaterialName.AutoEllipsis = false;
            this.labelMaterialName.CursorType = null;
            this.labelMaterialName.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelMaterialName.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelMaterialName.Location = new System.Drawing.Point(41, 158);
            this.labelMaterialName.Name = "labelMaterialName";
            this.labelMaterialName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelMaterialName.Size = new System.Drawing.Size(64, 17);
            this.labelMaterialName.TabIndex = 16;
            this.labelMaterialName.Text = "Tên vật tư";
            this.labelMaterialName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelMaterialName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelMaterialName, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelMaterialName, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelMaterialName, "");
            // 
            // textBoxMaterialName
            // 
            this.textBoxMaterialName.AcceptsReturn = false;
            this.textBoxMaterialName.AcceptsTab = false;
            this.textBoxMaterialName.AnimationSpeed = 200;
            this.textBoxMaterialName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxMaterialName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxMaterialName.BackColor = System.Drawing.Color.White;
            this.textBoxMaterialName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxMaterialName.BackgroundImage")));
            this.textBoxMaterialName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxMaterialName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxMaterialName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxMaterialName.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxMaterialName.BorderRadius = 10;
            this.textBoxMaterialName.BorderThickness = 1;
            this.textBoxMaterialName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxMaterialName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMaterialName.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxMaterialName.DefaultText = "";
            this.textBoxMaterialName.FillColor = System.Drawing.Color.White;
            this.textBoxMaterialName.ForeColor = System.Drawing.Color.Black;
            this.textBoxMaterialName.HideSelection = true;
            this.textBoxMaterialName.IconLeft = null;
            this.textBoxMaterialName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMaterialName.IconPadding = 10;
            this.textBoxMaterialName.IconRight = null;
            this.textBoxMaterialName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMaterialName.Lines = new string[0];
            this.textBoxMaterialName.Location = new System.Drawing.Point(155, 144);
            this.textBoxMaterialName.MaxLength = 32767;
            this.textBoxMaterialName.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxMaterialName.Modified = false;
            this.textBoxMaterialName.Multiline = false;
            this.textBoxMaterialName.Name = "textBoxMaterialName";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMaterialName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxMaterialName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMaterialName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMaterialName.OnIdleState = stateProperties12;
            this.textBoxMaterialName.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.textBoxMaterialName.PasswordChar = '\0';
            this.textBoxMaterialName.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxMaterialName.PlaceholderText = "Nhập tên vật tư";
            this.textBoxMaterialName.ReadOnly = false;
            this.textBoxMaterialName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxMaterialName.SelectedText = "";
            this.textBoxMaterialName.SelectionLength = 0;
            this.textBoxMaterialName.SelectionStart = 0;
            this.textBoxMaterialName.ShortcutsEnabled = true;
            this.textBoxMaterialName.Size = new System.Drawing.Size(291, 40);
            this.textBoxMaterialName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxMaterialName.TabIndex = 13;
            this.textBoxMaterialName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxMaterialName.TextMarginBottom = 0;
            this.textBoxMaterialName.TextMarginLeft = 3;
            this.textBoxMaterialName.TextMarginTop = 0;
            this.textBoxMaterialName.TextPlaceholder = "Nhập tên vật tư";
            this.bunifuToolTip1.SetToolTip(this.textBoxMaterialName, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxMaterialName, global::DO_AN_CUA_HAN.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxMaterialName, "Warning");
            this.textBoxMaterialName.UseSystemPasswordChar = false;
            this.textBoxMaterialName.WordWrap = true;
            this.textBoxMaterialName.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.textBoxMaterialName_KeyPress);
            // 
            // textBoxMaterialID
            // 
            this.textBoxMaterialID.AcceptsReturn = false;
            this.textBoxMaterialID.AcceptsTab = false;
            this.textBoxMaterialID.AnimationSpeed = 200;
            this.textBoxMaterialID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxMaterialID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxMaterialID.BackColor = System.Drawing.Color.White;
            this.textBoxMaterialID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxMaterialID.BackgroundImage")));
            this.textBoxMaterialID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxMaterialID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxMaterialID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxMaterialID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxMaterialID.BorderRadius = 20;
            this.textBoxMaterialID.BorderThickness = 1;
            this.textBoxMaterialID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxMaterialID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMaterialID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxMaterialID.DefaultText = "";
            this.textBoxMaterialID.FillColor = System.Drawing.Color.White;
            this.textBoxMaterialID.ForeColor = System.Drawing.Color.Black;
            this.textBoxMaterialID.HideSelection = true;
            this.textBoxMaterialID.IconLeft = null;
            this.textBoxMaterialID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMaterialID.IconPadding = 10;
            this.textBoxMaterialID.IconRight = null;
            this.textBoxMaterialID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxMaterialID.Lines = new string[0];
            this.textBoxMaterialID.Location = new System.Drawing.Point(155, 79);
            this.textBoxMaterialID.MaxLength = 32767;
            this.textBoxMaterialID.MinimumSize = new System.Drawing.Size(1, 1);
            this.textBoxMaterialID.Modified = false;
            this.textBoxMaterialID.Multiline = false;
            this.textBoxMaterialID.Name = "textBoxMaterialID";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMaterialID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxMaterialID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMaterialID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxMaterialID.OnIdleState = stateProperties16;
            this.textBoxMaterialID.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.textBoxMaterialID.PasswordChar = '\0';
            this.textBoxMaterialID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxMaterialID.PlaceholderText = "Nhập mã vật tư";
            this.textBoxMaterialID.ReadOnly = true;
            this.textBoxMaterialID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxMaterialID.SelectedText = "";
            this.textBoxMaterialID.SelectionLength = 0;
            this.textBoxMaterialID.SelectionStart = 0;
            this.textBoxMaterialID.ShortcutsEnabled = true;
            this.textBoxMaterialID.Size = new System.Drawing.Size(291, 40);
            this.textBoxMaterialID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxMaterialID.TabIndex = 12;
            this.textBoxMaterialID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxMaterialID.TextMarginBottom = 0;
            this.textBoxMaterialID.TextMarginLeft = 3;
            this.textBoxMaterialID.TextMarginTop = 0;
            this.textBoxMaterialID.TextPlaceholder = "Nhập mã vật tư";
            this.bunifuToolTip1.SetToolTip(this.textBoxMaterialID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxMaterialID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxMaterialID, "");
            this.textBoxMaterialID.UseSystemPasswordChar = false;
            this.textBoxMaterialID.WordWrap = true;
            // 
            // labelMaterialID
            // 
            this.labelMaterialID.AllowParentOverrides = false;
            this.labelMaterialID.AutoEllipsis = false;
            this.labelMaterialID.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelMaterialID.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelMaterialID.Font = new System.Drawing.Font("Cambria", 11F);
            this.labelMaterialID.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.labelMaterialID.Location = new System.Drawing.Point(41, 94);
            this.labelMaterialID.Name = "labelMaterialID";
            this.labelMaterialID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelMaterialID.Size = new System.Drawing.Size(59, 17);
            this.labelMaterialID.TabIndex = 2;
            this.labelMaterialID.Text = "Mã vật tư";
            this.labelMaterialID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelMaterialID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelMaterialID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelMaterialID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelMaterialID, "");
            // 
            // bunifuLabel24
            // 
            this.bunifuLabel24.AllowParentOverrides = false;
            this.bunifuLabel24.AutoEllipsis = false;
            this.bunifuLabel24.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel24.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel24.Font = new System.Drawing.Font("Cambria", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel24.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel24.Location = new System.Drawing.Point(213, 31);
            this.bunifuLabel24.Name = "bunifuLabel24";
            this.bunifuLabel24.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel24.Size = new System.Drawing.Size(86, 28);
            this.bunifuLabel24.TabIndex = 1;
            this.bunifuLabel24.Text = "VẬT TƯ";
            this.bunifuLabel24.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel24.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel24, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel24, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel24, "");
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::DO_AN_CUA_HAN.Properties.Resources.Biomedical_Fresh_And_Simple_Medical_Technology_Poster_Background_Wallpaper_Image_For_Free_Download___Pngtree_removebg_preview;
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(-39, 9);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(369, 369);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 34;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(221)))), ((int)(((byte)(85)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.DimGray;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // FormMaterialDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(616, 481);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "FormMaterialDetail";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormMaterialDetail";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonOk;
        private Bunifu.UI.WinForms.BunifuLabel labelPrice;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxPrice;
        private Bunifu.UI.WinForms.BunifuLabel labelMaterialName;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxMaterialName;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxMaterialID;
        private Bunifu.UI.WinForms.BunifuLabel labelMaterialID;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel24;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel labelQuantity;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxQuantity;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
    }
}