namespace DO_AN_CUA_HAN.View
{
    partial class FormHCDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormHCDetail));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuDropdownState = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDatePickerHospitalizate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuTextBoxReason = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxPatientID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxStaffID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxHICD = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(221)))), ((int)(((byte)(85)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.DimGray;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(157)))), ((int)(((byte)(191)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(205)))), ((int)(((byte)(197)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(109)))), ((int)(((byte)(160)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(798, 873);
            this.bunifuGradientPanel1.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel1.BorderRadius = 20;
            this.bunifuShadowPanel1.BorderThickness = 2;
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDropdownState);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDatePickerHospitalizate);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBoxReason);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBoxPatientID);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBoxStaffID);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBoxHICD);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel7);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel6);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.Font = new System.Drawing.Font("Cambria", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuShadowPanel1.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(52, 42);
            this.bunifuShadowPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.PaleTurquoise;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.MistyRose;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(113)))), ((int)(((byte)(199)))), ((int)(((byte)(205)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(694, 785);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuShadowPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuShadowPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuShadowPanel1, "");
            // 
            // bunifuDropdownState
            // 
            this.bunifuDropdownState.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDropdownState.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDropdownState.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDropdownState.BorderRadius = 1;
            this.bunifuDropdownState.Color = System.Drawing.Color.Silver;
            this.bunifuDropdownState.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bunifuDropdownState.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdownState.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDropdownState.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdownState.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bunifuDropdownState.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdownState.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bunifuDropdownState.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bunifuDropdownState.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bunifuDropdownState.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdownState.FillDropDown = true;
            this.bunifuDropdownState.FillIndicator = false;
            this.bunifuDropdownState.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bunifuDropdownState.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDropdownState.ForeColor = System.Drawing.Color.Black;
            this.bunifuDropdownState.FormattingEnabled = true;
            this.bunifuDropdownState.Icon = null;
            this.bunifuDropdownState.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdownState.IndicatorColor = System.Drawing.Color.Gray;
            this.bunifuDropdownState.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdownState.ItemBackColor = System.Drawing.Color.White;
            this.bunifuDropdownState.ItemBorderColor = System.Drawing.Color.White;
            this.bunifuDropdownState.ItemForeColor = System.Drawing.Color.Black;
            this.bunifuDropdownState.ItemHeight = 26;
            this.bunifuDropdownState.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDropdownState.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bunifuDropdownState.Items.AddRange(new object[] {
            "Chưa xác nhận",
            "Đã xác nhận"});
            this.bunifuDropdownState.ItemTopMargin = 3;
            this.bunifuDropdownState.Location = new System.Drawing.Point(68, 655);
            this.bunifuDropdownState.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuDropdownState.Name = "bunifuDropdownState";
            this.bunifuDropdownState.Size = new System.Drawing.Size(565, 32);
            this.bunifuDropdownState.TabIndex = 16;
            this.bunifuDropdownState.Text = null;
            this.bunifuDropdownState.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdownState.TextLeftMargin = 5;
            this.bunifuToolTip1.SetToolTip(this.bunifuDropdownState, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuDropdownState, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuDropdownState, "");
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Thoát";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges1;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.IdleBorderRadius = 15;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(554, 706);
            this.bunifuButton2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 15;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 15;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 15;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 15;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(109, 48);
            this.bunifuButton2.TabIndex = 15;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton2, "");
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Đồng ý";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.IdleBorderRadius = 15;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(413, 706);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 15;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 15;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 15;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 15;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(109, 48);
            this.bunifuButton1.TabIndex = 14;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton1, "");
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bunifuDatePickerHospitalizate
            // 
            this.bunifuDatePickerHospitalizate.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePickerHospitalizate.BorderRadius = 1;
            this.bunifuDatePickerHospitalizate.Color = System.Drawing.Color.Gainsboro;
            this.bunifuDatePickerHospitalizate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePickerHospitalizate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePickerHospitalizate.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePickerHospitalizate.DisplayWeekNumbers = false;
            this.bunifuDatePickerHospitalizate.DPHeight = 0;
            this.bunifuDatePickerHospitalizate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePickerHospitalizate.FillDatePicker = false;
            this.bunifuDatePickerHospitalizate.Font = new System.Drawing.Font("Cambria", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDatePickerHospitalizate.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePickerHospitalizate.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePickerHospitalizate.Icon")));
            this.bunifuDatePickerHospitalizate.IconColor = System.Drawing.Color.DimGray;
            this.bunifuDatePickerHospitalizate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePickerHospitalizate.LeftTextMargin = 5;
            this.bunifuDatePickerHospitalizate.Location = new System.Drawing.Point(68, 561);
            this.bunifuDatePickerHospitalizate.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuDatePickerHospitalizate.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePickerHospitalizate.Name = "bunifuDatePickerHospitalizate";
            this.bunifuDatePickerHospitalizate.Size = new System.Drawing.Size(567, 32);
            this.bunifuDatePickerHospitalizate.TabIndex = 12;
            this.bunifuToolTip1.SetToolTip(this.bunifuDatePickerHospitalizate, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuDatePickerHospitalizate, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuDatePickerHospitalizate, "");
            this.bunifuDatePickerHospitalizate.Value = new System.DateTime(2023, 12, 9, 17, 17, 0, 0);
            // 
            // bunifuTextBoxReason
            // 
            this.bunifuTextBoxReason.AcceptsReturn = false;
            this.bunifuTextBoxReason.AcceptsTab = false;
            this.bunifuTextBoxReason.AnimationSpeed = 200;
            this.bunifuTextBoxReason.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxReason.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxReason.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxReason.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxReason.BackgroundImage")));
            this.bunifuTextBoxReason.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxReason.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxReason.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxReason.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxReason.BorderRadius = 1;
            this.bunifuTextBoxReason.BorderThickness = 1;
            this.bunifuTextBoxReason.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxReason.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxReason.DefaultFont = new System.Drawing.Font("Cambria", 9.75F);
            this.bunifuTextBoxReason.DefaultText = "";
            this.bunifuTextBoxReason.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxReason.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxReason.HideSelection = true;
            this.bunifuTextBoxReason.IconLeft = null;
            this.bunifuTextBoxReason.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxReason.IconPadding = 10;
            this.bunifuTextBoxReason.IconRight = null;
            this.bunifuTextBoxReason.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxReason.Lines = new string[0];
            this.bunifuTextBoxReason.Location = new System.Drawing.Point(68, 459);
            this.bunifuTextBoxReason.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxReason.MaxLength = 32767;
            this.bunifuTextBoxReason.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxReason.Modified = false;
            this.bunifuTextBoxReason.Multiline = true;
            this.bunifuTextBoxReason.Name = "bunifuTextBoxReason";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxReason.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxReason.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxReason.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxReason.OnIdleState = stateProperties4;
            this.bunifuTextBoxReason.Padding = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxReason.PasswordChar = '\0';
            this.bunifuTextBoxReason.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxReason.PlaceholderText = "Nhập lý do";
            this.bunifuTextBoxReason.ReadOnly = false;
            this.bunifuTextBoxReason.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxReason.SelectedText = "";
            this.bunifuTextBoxReason.SelectionLength = 0;
            this.bunifuTextBoxReason.SelectionStart = 0;
            this.bunifuTextBoxReason.ShortcutsEnabled = true;
            this.bunifuTextBoxReason.Size = new System.Drawing.Size(567, 64);
            this.bunifuTextBoxReason.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxReason.TabIndex = 10;
            this.bunifuTextBoxReason.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxReason.TextMarginBottom = 0;
            this.bunifuTextBoxReason.TextMarginLeft = 3;
            this.bunifuTextBoxReason.TextMarginTop = 0;
            this.bunifuTextBoxReason.TextPlaceholder = "Nhập lý do";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxReason, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxReason, global::DO_AN_CUA_HAN.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxReason, "Warning");
            this.bunifuTextBoxReason.UseSystemPasswordChar = false;
            this.bunifuTextBoxReason.WordWrap = true;
            this.bunifuTextBoxReason.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.bunifuTextBoxReason_KeyPress);
            // 
            // bunifuTextBoxPatientID
            // 
            this.bunifuTextBoxPatientID.AcceptsReturn = false;
            this.bunifuTextBoxPatientID.AcceptsTab = false;
            this.bunifuTextBoxPatientID.AnimationSpeed = 200;
            this.bunifuTextBoxPatientID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPatientID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPatientID.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxPatientID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPatientID.BackgroundImage")));
            this.bunifuTextBoxPatientID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPatientID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPatientID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPatientID.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPatientID.BorderRadius = 1;
            this.bunifuTextBoxPatientID.BorderThickness = 1;
            this.bunifuTextBoxPatientID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPatientID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPatientID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F);
            this.bunifuTextBoxPatientID.DefaultText = "";
            this.bunifuTextBoxPatientID.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPatientID.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxPatientID.HideSelection = true;
            this.bunifuTextBoxPatientID.IconLeft = null;
            this.bunifuTextBoxPatientID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPatientID.IconPadding = 10;
            this.bunifuTextBoxPatientID.IconRight = null;
            this.bunifuTextBoxPatientID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPatientID.Lines = new string[0];
            this.bunifuTextBoxPatientID.Location = new System.Drawing.Point(68, 360);
            this.bunifuTextBoxPatientID.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxPatientID.MaxLength = 32767;
            this.bunifuTextBoxPatientID.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPatientID.Modified = false;
            this.bunifuTextBoxPatientID.Multiline = false;
            this.bunifuTextBoxPatientID.Name = "bunifuTextBoxPatientID";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPatientID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPatientID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPatientID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPatientID.OnIdleState = stateProperties8;
            this.bunifuTextBoxPatientID.Padding = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxPatientID.PasswordChar = '\0';
            this.bunifuTextBoxPatientID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxPatientID.PlaceholderText = "Nhập mã bệnh nhân";
            this.bunifuTextBoxPatientID.ReadOnly = true;
            this.bunifuTextBoxPatientID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPatientID.SelectedText = "";
            this.bunifuTextBoxPatientID.SelectionLength = 0;
            this.bunifuTextBoxPatientID.SelectionStart = 0;
            this.bunifuTextBoxPatientID.ShortcutsEnabled = true;
            this.bunifuTextBoxPatientID.Size = new System.Drawing.Size(567, 39);
            this.bunifuTextBoxPatientID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxPatientID.TabIndex = 9;
            this.bunifuTextBoxPatientID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxPatientID.TextMarginBottom = 0;
            this.bunifuTextBoxPatientID.TextMarginLeft = 3;
            this.bunifuTextBoxPatientID.TextMarginTop = 0;
            this.bunifuTextBoxPatientID.TextPlaceholder = "Nhập mã bệnh nhân";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxPatientID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxPatientID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxPatientID, "");
            this.bunifuTextBoxPatientID.UseSystemPasswordChar = false;
            this.bunifuTextBoxPatientID.WordWrap = true;
            // 
            // bunifuTextBoxStaffID
            // 
            this.bunifuTextBoxStaffID.AcceptsReturn = false;
            this.bunifuTextBoxStaffID.AcceptsTab = false;
            this.bunifuTextBoxStaffID.AnimationSpeed = 200;
            this.bunifuTextBoxStaffID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxStaffID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxStaffID.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxStaffID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxStaffID.BackgroundImage")));
            this.bunifuTextBoxStaffID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxStaffID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxStaffID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxStaffID.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxStaffID.BorderRadius = 1;
            this.bunifuTextBoxStaffID.BorderThickness = 1;
            this.bunifuTextBoxStaffID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxStaffID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxStaffID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F);
            this.bunifuTextBoxStaffID.DefaultText = "";
            this.bunifuTextBoxStaffID.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxStaffID.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxStaffID.HideSelection = true;
            this.bunifuTextBoxStaffID.IconLeft = null;
            this.bunifuTextBoxStaffID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxStaffID.IconPadding = 10;
            this.bunifuTextBoxStaffID.IconRight = null;
            this.bunifuTextBoxStaffID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxStaffID.Lines = new string[0];
            this.bunifuTextBoxStaffID.Location = new System.Drawing.Point(68, 262);
            this.bunifuTextBoxStaffID.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxStaffID.MaxLength = 32767;
            this.bunifuTextBoxStaffID.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxStaffID.Modified = false;
            this.bunifuTextBoxStaffID.Multiline = false;
            this.bunifuTextBoxStaffID.Name = "bunifuTextBoxStaffID";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxStaffID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxStaffID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxStaffID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxStaffID.OnIdleState = stateProperties12;
            this.bunifuTextBoxStaffID.Padding = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxStaffID.PasswordChar = '\0';
            this.bunifuTextBoxStaffID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxStaffID.PlaceholderText = "Nhập mã nhân viên phụ trách";
            this.bunifuTextBoxStaffID.ReadOnly = true;
            this.bunifuTextBoxStaffID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxStaffID.SelectedText = "";
            this.bunifuTextBoxStaffID.SelectionLength = 0;
            this.bunifuTextBoxStaffID.SelectionStart = 0;
            this.bunifuTextBoxStaffID.ShortcutsEnabled = true;
            this.bunifuTextBoxStaffID.Size = new System.Drawing.Size(567, 39);
            this.bunifuTextBoxStaffID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxStaffID.TabIndex = 8;
            this.bunifuTextBoxStaffID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxStaffID.TextMarginBottom = 0;
            this.bunifuTextBoxStaffID.TextMarginLeft = 3;
            this.bunifuTextBoxStaffID.TextMarginTop = 0;
            this.bunifuTextBoxStaffID.TextPlaceholder = "Nhập mã nhân viên phụ trách";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxStaffID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxStaffID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxStaffID, "");
            this.bunifuTextBoxStaffID.UseSystemPasswordChar = false;
            this.bunifuTextBoxStaffID.WordWrap = true;
            // 
            // bunifuTextBoxHICD
            // 
            this.bunifuTextBoxHICD.AcceptsReturn = false;
            this.bunifuTextBoxHICD.AcceptsTab = false;
            this.bunifuTextBoxHICD.AnimationSpeed = 200;
            this.bunifuTextBoxHICD.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxHICD.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxHICD.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxHICD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxHICD.BackgroundImage")));
            this.bunifuTextBoxHICD.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxHICD.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxHICD.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxHICD.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxHICD.BorderRadius = 1;
            this.bunifuTextBoxHICD.BorderThickness = 1;
            this.bunifuTextBoxHICD.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxHICD.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxHICD.DefaultFont = new System.Drawing.Font("Cambria", 9.75F);
            this.bunifuTextBoxHICD.DefaultText = "";
            this.bunifuTextBoxHICD.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxHICD.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBoxHICD.HideSelection = true;
            this.bunifuTextBoxHICD.IconLeft = null;
            this.bunifuTextBoxHICD.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxHICD.IconPadding = 10;
            this.bunifuTextBoxHICD.IconRight = null;
            this.bunifuTextBoxHICD.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxHICD.Lines = new string[0];
            this.bunifuTextBoxHICD.Location = new System.Drawing.Point(68, 160);
            this.bunifuTextBoxHICD.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxHICD.MaxLength = 32767;
            this.bunifuTextBoxHICD.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxHICD.Modified = false;
            this.bunifuTextBoxHICD.Multiline = false;
            this.bunifuTextBoxHICD.Name = "bunifuTextBoxHICD";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxHICD.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxHICD.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxHICD.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxHICD.OnIdleState = stateProperties16;
            this.bunifuTextBoxHICD.Padding = new System.Windows.Forms.Padding(4);
            this.bunifuTextBoxHICD.PasswordChar = '\0';
            this.bunifuTextBoxHICD.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBoxHICD.PlaceholderText = "Nhập mã phiếu nhập viện";
            this.bunifuTextBoxHICD.ReadOnly = true;
            this.bunifuTextBoxHICD.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxHICD.SelectedText = "";
            this.bunifuTextBoxHICD.SelectionLength = 0;
            this.bunifuTextBoxHICD.SelectionStart = 0;
            this.bunifuTextBoxHICD.ShortcutsEnabled = true;
            this.bunifuTextBoxHICD.Size = new System.Drawing.Size(567, 39);
            this.bunifuTextBoxHICD.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxHICD.TabIndex = 7;
            this.bunifuTextBoxHICD.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxHICD.TextMarginBottom = 0;
            this.bunifuTextBoxHICD.TextMarginLeft = 3;
            this.bunifuTextBoxHICD.TextMarginTop = 0;
            this.bunifuTextBoxHICD.TextPlaceholder = "Nhập mã phiếu nhập viện";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxHICD, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxHICD, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxHICD, "");
            this.bunifuTextBoxHICD.UseSystemPasswordChar = false;
            this.bunifuTextBoxHICD.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel7.Location = new System.Drawing.Point(68, 625);
            this.bunifuLabel7.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(64, 17);
            this.bunifuLabel7.TabIndex = 6;
            this.bunifuLabel7.Text = "Trạng thái";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel7, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel7, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel7, "");
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel6.Location = new System.Drawing.Point(68, 531);
            this.bunifuLabel6.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(96, 17);
            this.bunifuLabel6.TabIndex = 5;
            this.bunifuLabel6.Text = "Ngày nhập viện";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel6, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel6, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel6, "");
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel5.Location = new System.Drawing.Point(79, 429);
            this.bunifuLabel5.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(35, 17);
            this.bunifuLabel5.TabIndex = 4;
            this.bunifuLabel5.Text = "Lý do";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel5, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel5, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel5, "");
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel4.Location = new System.Drawing.Point(79, 330);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(87, 17);
            this.bunifuLabel4.TabIndex = 3;
            this.bunifuLabel4.Text = "Mã bệnh nhân";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel4, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel4, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel4, "");
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel3.Location = new System.Drawing.Point(79, 231);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(146, 17);
            this.bunifuLabel3.TabIndex = 2;
            this.bunifuLabel3.Text = "Mã nhân viên phụ trách";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel3, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel3, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel3, "");
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Cambria", 11F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel2.Location = new System.Drawing.Point(79, 129);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(121, 17);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "Mã phiếu nhập viện";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel2, "");
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cambria", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuLabel1.Location = new System.Drawing.Point(281, 50);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(197, 28);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "PHIẾU NHẬP VIỆN";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 94;
            this.bunifuPictureBox1.Image = global::DO_AN_CUA_HAN.Properties.Resources._2318_R0lVIEFOTiAwNzAtMTA5_removebg_preview;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(110, -37);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(189, 189);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 13;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // FormHCDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(798, 873);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Font = new System.Drawing.Font("Cambria", 11F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "FormHCDetail";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormHCDetail";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePickerHospitalizate;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxReason;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPatientID;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxStaffID;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxHICD;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuDropdown bunifuDropdownState;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
    }
}